UPDATE cyclists SET name="VAN DER POEL Mathieu" WHERE cyclistId=1;
UPDATE cyclists SET name="PHILIPSEN Jasper" WHERE cyclistId=2;
UPDATE cyclists SET name="GROVES Kaden" WHERE cyclistId=3;
UPDATE cyclists SET name="KRAGH ANDERSEN Kragh" WHERE cyclistId=4;
UPDATE cyclists SET name="KIELICH Timo" WHERE cyclistId=5;
UPDATE cyclists SET name="HERMANS Quinten" WHERE cyclistId=6;
UPDATE cyclists SET name="VAN TRICHT Stan" WHERE cyclistId=7;
UPDATE cyclists SET name="VERMEERSCH Gianni" WHERE cyclistId=8;
UPDATE cyclists SET name="LAURANCE Axel" WHERE cyclistId=9;
UPDATE cyclists SET name="BALLERSTEDT Maurice" WHERE cyclistId=10;
UPDATE cyclists SET name="BAYER Tobias" WHERE cyclistId=11;
UPDATE cyclists SET name="BOVEN Lars" WHERE cyclistId=12;
UPDATE cyclists SET name="CONCI Nicola" WHERE cyclistId=13;
UPDATE cyclists SET name="DILLIER Silvan" WHERE cyclistId=14;
UPDATE cyclists SET name="GAZE Samuel" WHERE cyclistId=15;
UPDATE cyclists SET name="GHYS Robbe" WHERE cyclistId=16;
UPDATE cyclists SET name="GOGL Michael" WHERE cyclistId=17;
UPDATE cyclists SET name="HOLLMANN Juri" WHERE cyclistId=18;
UPDATE cyclists SET name="JENSSEN Jimmy" WHERE cyclistId=19;
UPDATE cyclists SET name="LEYSEN Senne" WHERE cyclistId=20;
UPDATE cyclists SET name="MEURISSE Xandro" WHERE cyclistId=21;
UPDATE cyclists SET name="OSBORNE Jason" WHERE cyclistId=22;
UPDATE cyclists SET name="PLANCKAERT Edward" WHERE cyclistId=23;
UPDATE cyclists SET name="PLOWRIGHT Jensen" WHERE cyclistId=24;
UPDATE cyclists SET name="RICKAERT Jonas" WHERE cyclistId=25;
UPDATE cyclists SET name="RIESEBEEK Oscar" WHERE cyclistId=26;
UPDATE cyclists SET name="SINKELDAM Ramon" WHERE cyclistId=27;
UPDATE cyclists SET name="UHLIG Henri" WHERE cyclistId=28;
UPDATE cyclists SET name="VAN DEN BOSSCHE Fabio" WHERE cyclistId=29;
UPDATE cyclists SET name="VERGALLITO Luca" WHERE cyclistId=30;
UPDATE cyclists SET name="DEMARE Arnaud" WHERE cyclistId=31;
UPDATE cyclists SET name="MOZZATO Luca" WHERE cyclistId=32;
UPDATE cyclists SET name="ALBANEZE Vincenzo" WHERE cyclistId=33;
UPDATE cyclists SET name="RODRIGUEZ Cristian" WHERE cyclistId=34;
UPDATE cyclists SET name="VAUQUELIN Kévin" WHERE cyclistId=35;
UPDATE cyclists SET name="BIERMANS Jenthe" WHERE cyclistId=36;
UPDATE cyclists SET name="VENTURINI Clément" WHERE cyclistId=37;
UPDATE cyclists SET name="CHAMPOUSSIN Clément" WHERE cyclistId=38;
UPDATE cyclists SET name="LOUVEL Matis" WHERE cyclistId=39;
UPDATE cyclists SET name="GESBERT Elie" WHERE cyclistId=40;
UPDATE cyclists SET name="SENECHAL Florian" WHERE cyclistId=41;
UPDATE cyclists SET name="BARRE Louis" WHERE cyclistId=42;
UPDATE cyclists SET name="CAPIOT Amaury" WHERE cyclistId=43;
UPDATE cyclists SET name="COSTIOU Ewen" WHERE cyclistId=44;
UPDATE cyclists SET name="DEKKER David" WHERE cyclistId=45;
UPDATE cyclists SET name="DELAPLACE Anthony" WHERE cyclistId=46;
UPDATE cyclists SET name="GARCÍA PIERNA Raúl" WHERE cyclistId=47;
UPDATE cyclists SET name="GRONDIN Donovan" WHERE cyclistId=48;
UPDATE cyclists SET name="GUERNALEC Thibault" WHERE cyclistId=49;
UPDATE cyclists SET name="GUGLIELMI Simon" WHERE cyclistId=50;
UPDATE cyclists SET name="HUYS Laurens" WHERE cyclistId=51;
UPDATE cyclists SET name="LE BERRE Mathis" WHERE cyclistId=52;
UPDATE cyclists SET name="LEDANOIS Kevin" WHERE cyclistId=53;
UPDATE cyclists SET name="MCLAY Daniel" WHERE cyclistId=54;
UPDATE cyclists SET name="OWSIAN Łukasz" WHERE cyclistId=55;
UPDATE cyclists SET name="RIES Michel" WHERE cyclistId=56;
UPDATE cyclists SET name="RIOU Alan" WHERE cyclistId=57;
UPDATE cyclists SET name="SCOTSON Miles" WHERE cyclistId=58;
UPDATE cyclists SET name="VERRE Alessandro" WHERE cyclistId=59;
UPDATE cyclists SET name="LUTSENKO Alexey" WHERE cyclistId=60;
UPDATE cyclists SET name="CAVENDISH Mark" WHERE cyclistId=61;
UPDATE cyclists SET name="MULUBRHAN Henok" WHERE cyclistId=62;
UPDATE cyclists SET name="VELASCO Simone" WHERE cyclistId=63;
UPDATE cyclists SET name="BALLERINI Davide" WHERE cyclistId=64;
UPDATE cyclists SET name="BOL Cees" WHERE cyclistId=65;
UPDATE cyclists SET name="FORTUNATO Lorenzo" WHERE cyclistId=66;
UPDATE cyclists SET name="KUZMIN Anton" WHERE cyclistId=67;
UPDATE cyclists SET name="MARUKHIN Daniil" WHERE cyclistId=68;
UPDATE cyclists SET name="BRUSSENSKIY Gleb" WHERE cyclistId=69;
UPDATE cyclists SET name="GIDICH Yevgeniy" WHERE cyclistId=70;
UPDATE cyclists SET name="TEJADA Harold" WHERE cyclistId=71;
UPDATE cyclists SET name="BATTISTELLA Samuele" WHERE cyclistId=72;
UPDATE cyclists SET name="CHARMIG Anthon" WHERE cyclistId=73;
UPDATE cyclists SET name="CHZHAN Igor" WHERE cyclistId=74;
UPDATE cyclists SET name="FEDOROV Yevgeniy" WHERE cyclistId=75;
UPDATE cyclists SET name="GAROFOLI Gianmarco" WHERE cyclistId=76;
UPDATE cyclists SET name="GAZZOLI Michele" WHERE cyclistId=77;
UPDATE cyclists SET name="GRUZDEV Dmitriy" WHERE cyclistId=78;
UPDATE cyclists SET name="KANTER Max" WHERE cyclistId=79;
UPDATE cyclists SET name="LOPEZ Harold Martin" WHERE cyclistId=80;
UPDATE cyclists SET name="MØRKØV Michael" WHERE cyclistId=81;
UPDATE cyclists SET name="PRONSKIY Vadim" WHERE cyclistId=82;
UPDATE cyclists SET name="SCARONI Christian" WHERE cyclistId=83;
UPDATE cyclists SET name="SCHELLING Ide" WHERE cyclistId=84;
UPDATE cyclists SET name="SELIG Rüdiger" WHERE cyclistId=85;
UPDATE cyclists SET name="SYRITSA Gleb" WHERE cyclistId=86;
UPDATE cyclists SET name="UMBA Santiago" WHERE cyclistId=87;
UPDATE cyclists SET name="VINOKUROV Nicolas" WHERE cyclistId=88;
UPDATE cyclists SET name="BILBAO Pello" WHERE cyclistId=89;
UPDATE cyclists SET name="MOHORIC Matej" WHERE cyclistId=90;
UPDATE cyclists SET name="CARUSO Damiano" WHERE cyclistId=91;
UPDATE cyclists SET name="BUITRAGO Santiago" WHERE cyclistId=92;
UPDATE cyclists SET name="POELS Wout" WHERE cyclistId=93;
UPDATE cyclists SET name="HAIG Jack" WHERE cyclistId=94;
UPDATE cyclists SET name="BAUHAUS Phil" WHERE cyclistId=95;
UPDATE cyclists SET name="WRIGHT Fred" WHERE cyclistId=96;
UPDATE cyclists SET name="ARASHIRO Yukiya" WHERE cyclistId=97;
UPDATE cyclists SET name="ARNDT Nikias" WHERE cyclistId=98;
UPDATE cyclists SET name="BRUTTOMESSO Alberto" WHERE cyclistId=99;
UPDATE cyclists SET name="BURATTI Nicolò" WHERE cyclistId=100;
UPDATE cyclists SET name="GOVEKAR Matevž" WHERE cyclistId=101;
UPDATE cyclists SET name="GRADEK Kamil" WHERE cyclistId=102;
UPDATE cyclists SET name="KEPPLINGER Rainer" WHERE cyclistId=103;
UPDATE cyclists SET name="MADAN Ahmed" WHERE cyclistId=104;
UPDATE cyclists SET name="MIHOLJEVIĆ Fran" WHERE cyclistId=105;
UPDATE cyclists SET name="PASQUALON Andrea" WHERE cyclistId=106;
UPDATE cyclists SET name="PICKERING Finlay" WHERE cyclistId=107;
UPDATE cyclists SET name="PRICE-PEJTERSEN Johan" WHERE cyclistId=108;
UPDATE cyclists SET name="RAJOVIĆ Dušan" WHERE cyclistId=109;
UPDATE cyclists SET name="SCOTT Cameron" WHERE cyclistId=110;
UPDATE cyclists SET name="SÜTTERLIN Jasha" WHERE cyclistId=111;
UPDATE cyclists SET name="TIBERI Antonio" WHERE cyclistId=112;
UPDATE cyclists SET name="TRÆEN Torstein" WHERE cyclistId=113;
UPDATE cyclists SET name="TU Sergio" WHERE cyclistId=114;
UPDATE cyclists SET name="ZAMBANINI Edoardo" WHERE cyclistId=115;
UPDATE cyclists SET name="VILLA Giacomo" WHERE cyclistId=116;
UPDATE cyclists SET name="BLOUWE Louis" WHERE cyclistId=117;
UPDATE cyclists SET name="DE MEESTER Luca" WHERE cyclistId=118;
UPDATE cyclists SET name="DE TIER Floris" WHERE cyclistId=119;
UPDATE cyclists SET name="DESAL Ceriel" WHERE cyclistId=120;
UPDATE cyclists SET name="MATTHYS Louka" WHERE cyclistId=121;
UPDATE cyclists SET name="MEENS Johan" WHERE cyclistId=122;
UPDATE cyclists SET name="MERTENS Julian" WHERE cyclistId=123;
UPDATE cyclists SET name="PERSICO Davide" WHERE cyclistId=124;
UPDATE cyclists SET name="PEYSKENS Dimitri" WHERE cyclistId=125;
UPDATE cyclists SET name="PORTSMOUTH Tom" WHERE cyclistId=126;
UPDATE cyclists SET name="SALBY Alexander" WHERE cyclistId=127;
UPDATE cyclists SET name="TEUGELS Lennert" WHERE cyclistId=128;
UPDATE cyclists SET name="TIZZA Marco" WHERE cyclistId=129;
UPDATE cyclists SET name="VAN BOVEN Luca" WHERE cyclistId=130;
UPDATE cyclists SET name="VAN DER BEKEN Aaron" WHERE cyclistId=131;
UPDATE cyclists SET name="VAN ROOY Kenneth" WHERE cyclistId=132;
UPDATE cyclists SET name="VANDEPITTE Nathan" WHERE cyclistId=133;
UPDATE cyclists SET name="VERMOOTE Jelle" WHERE cyclistId=134;
UPDATE cyclists SET name="VLIEGEN Loic" WHERE cyclistId=135;
UPDATE cyclists SET name="WEEMAES Sasha" WHERE cyclistId=136;
UPDATE cyclists SET name="ROGLIC Primoz" WHERE cyclistId=137;
UPDATE cyclists SET name="VLASOV Alexander" WHERE cyclistId=138;
UPDATE cyclists SET name="HINDLEY Jai" WHERE cyclistId=139;
UPDATE cyclists SET name="KAMNA Lennard" WHERE cyclistId=140;
UPDATE cyclists SET name="MEEUS Jordi" WHERE cyclistId=141;
UPDATE cyclists SET name="VAN POPPEL Danny" WHERE cyclistId=142;
UPDATE cyclists SET name="WELSFORD Sam" WHERE cyclistId=143;
UPDATE cyclists SET name="DENZ Nico" WHERE cyclistId=144;
UPDATE cyclists SET name="HIGUITA Sergio" WHERE cyclistId=145;
UPDATE cyclists SET name="ADRIA Roger" WHERE cyclistId=146;
UPDATE cyclists SET name="BUCHMANN Emmanuel" WHERE cyclistId=147;
UPDATE cyclists SET name="MARTINEZ Daniel Felipe" WHERE cyclistId=148;
UPDATE cyclists SET name="ZWIEHOFF Ben" WHERE cyclistId=149;
UPDATE cyclists SET name="ALEOTTI Giovanni" WHERE cyclistId=150;
UPDATE cyclists SET name="BENEDETTI Cesare" WHERE cyclistId=151;
UPDATE cyclists SET name="GAMPER Patrick" WHERE cyclistId=152;
UPDATE cyclists SET name="HAJEK Alexander" WHERE cyclistId=153;
UPDATE cyclists SET name="HALLER Marco" WHERE cyclistId=154;
UPDATE cyclists SET name="HERZOG Emil" WHERE cyclistId=155;
UPDATE cyclists SET name="JUNGELS Bob" WHERE cyclistId=156;
UPDATE cyclists SET name="KOCH Jonas" WHERE cyclistId=157;
UPDATE cyclists SET name="LIPOWITZ Florian" WHERE cyclistId=158;
UPDATE cyclists SET name="LÜHRS Luis-Joe" WHERE cyclistId=159;
UPDATE cyclists SET name="MACIEJUK Filip" WHERE cyclistId=160;
UPDATE cyclists SET name="MULLEN Ryan" WHERE cyclistId=161;
UPDATE cyclists SET name="PALZER Anton" WHERE cyclistId=162;
UPDATE cyclists SET name="SCHACHMANN Maximilian" WHERE cyclistId=163;
UPDATE cyclists SET name="SOBRERO Matteo" WHERE cyclistId=164;
UPDATE cyclists SET name="WANDAHL Frederik" WHERE cyclistId=165;
UPDATE cyclists SET name="SAINBAYAR Jambaljamts" WHERE cyclistId=166;
UPDATE cyclists SET name="FAGUNDEZ Eric Antonio" WHERE cyclistId=167;
UPDATE cyclists SET name="JACKSON George" WHERE cyclistId=168;
UPDATE cyclists SET name="GATE Aaron" WHERE cyclistId=169;
UPDATE cyclists SET name="ALLENO Clément" WHERE cyclistId=170;
UPDATE cyclists SET name="ALVAREZ Rodrigo" WHERE cyclistId=171;
UPDATE cyclists SET name="ANGULO Antonio" WHERE cyclistId=172;
UPDATE cyclists SET name="APARICIO Mario" WHERE cyclistId=173;
UPDATE cyclists SET name="BOL Jetse" WHERE cyclistId=174;
UPDATE cyclists SET name="BOUGLAS Georgios" WHERE cyclistId=175;
UPDATE cyclists SET name="CHUMIL Sergio Geovani" WHERE cyclistId=176;
UPDATE cyclists SET name="DELGADO David" WHERE cyclistId=177;
UPDATE cyclists SET name="DIAZ José Manuel" WHERE cyclistId=178;
UPDATE cyclists SET name="EZQUERRA Jesus" WHERE cyclistId=179;
UPDATE cyclists SET name="FER0DEZ Sinuhé" WHERE cyclistId=180;
UPDATE cyclists SET name="FRANCO Alejandro" WHERE cyclistId=181;
UPDATE cyclists SET name="FUENTES Angel" WHERE cyclistId=182;
UPDATE cyclists SET name="LANGELLOTTI Victor" WHERE cyclistId=183;
UPDATE cyclists SET name="MORA Sebastian" WHERE cyclistId=184;
UPDATE cyclists SET name="OKAMIKA Ander" WHERE cyclistId=185;
UPDATE cyclists SET name="PELEGRI Oscar" WHERE cyclistId=186;
UPDATE cyclists SET name="AULAR Orluis" WHERE cyclistId=187;
UPDATE cyclists SET name="BERWICK Sebastian" WHERE cyclistId=188;
UPDATE cyclists SET name="ARRIOLA-BENGOA Julen" WHERE cyclistId=189;
UPDATE cyclists SET name="BABOR Daniel" WHERE cyclistId=190;
UPDATE cyclists SET name="BALDERSTONE Abel" WHERE cyclistId=191;
UPDATE cyclists SET name="BARTA Tomas" WHERE cyclistId=192;
UPDATE cyclists SET name="CEPEDA Jefferson Alveiro" WHERE cyclistId=193;
UPDATE cyclists SET name="ETXEBERRIA Josu" WHERE cyclistId=194;
UPDATE cyclists SET name="FER0DEZ Samuel" WHERE cyclistId=195;
UPDATE cyclists SET name="GONZALEZ David" WHERE cyclistId=196;
UPDATE cyclists SET name="GUARDENO Jaume" WHERE cyclistId=197;
UPDATE cyclists SET name="HAILEMICHAEL Mulu Knife" WHERE cyclistId=198;
UPDATE cyclists SET name="JOHNSTON Calum" WHERE cyclistId=199;
UPDATE cyclists SET name="LOPEZ Joseba" WHERE cyclistId=200;
UPDATE cyclists SET name="MURGUIALDAY Jokin" WHERE cyclistId=201;
UPDATE cyclists SET name="NICOLAU Joel" WHERE cyclistId=202;
UPDATE cyclists SET name="PRADES Eduard" WHERE cyclistId=203;
UPDATE cyclists SET name="SCHLEGEL Michal" WHERE cyclistId=204;
UPDATE cyclists SET name="SILVA Guillermo" WHERE cyclistId=205;
UPDATE cyclists SET name="SORARRAIN Gorka" WHERE cyclistId=206;
UPDATE cyclists SET name="BARCELO Fer0do" WHERE cyclistId=207;
UPDATE cyclists SET name="LEITAO Iuri" WHERE cyclistId=208;
UPDATE cyclists SET name="MARTIN Guillaume" WHERE cyclistId=209;
UPDATE cyclists SET name="IZAGIRRE Ion" WHERE cyclistId=210;
UPDATE cyclists SET name="ZINGLE Axel" WHERE cyclistId=211;
UPDATE cyclists SET name="COQUARD Bryan" WHERE cyclistId=212;
UPDATE cyclists SET name="HERRADA Jesus" WHERE cyclistId=213;
UPDATE cyclists SET name="PEREZ Anthony" WHERE cyclistId=214;
UPDATE cyclists SET name="OLDANI Stefano" WHERE cyclistId=215;
UPDATE cyclists SET name="ALLEGAERT Piet" WHERE cyclistId=216;
UPDATE cyclists SET name="IZAGIRRE Gorka" WHERE cyclistId=217;
UPDATE cyclists SET name="RENARD Alexis" WHERE cyclistId=218;
UPDATE cyclists SET name="ANIOŁKOWSKI Stanisław" WHERE cyclistId=219;
UPDATE cyclists SET name="CHAMPION Thomas" WHERE cyclistId=220;
UPDATE cyclists SET name="DE GENDT Aimé" WHERE cyclistId=221;
UPDATE cyclists SET name="DEBEAUMARCHE Nicolas" WHERE cyclistId=222;
UPDATE cyclists SET name="ELISSONDE Kenny" WHERE cyclistId=223;
UPDATE cyclists SET name="FERNÁNDEZ Rubén" WHERE cyclistId=224;
UPDATE cyclists SET name="FINE Eddy" WHERE cyclistId=225;
UPDATE cyclists SET name="FRETIN Milan" WHERE cyclistId=226;
UPDATE cyclists SET name="GESCHKE Simon" WHERE cyclistId=227;
UPDATE cyclists SET name="GOUGEARD Alexis" WHERE cyclistId=228;
UPDATE cyclists SET name="HERMANS Ben" WHERE cyclistId=229;
UPDATE cyclists SET name="KNIGHT Oliver" WHERE cyclistId=230;
UPDATE cyclists SET name="LASTRA Jonathan" WHERE cyclistId=231;
UPDATE cyclists SET name="MAHOUDO Nolann" WHERE cyclistId=232;
UPDATE cyclists SET name="MARIAULT Axel" WHERE cyclistId=233;
UPDATE cyclists SET name="NOPPE Christophe" WHERE cyclistId=234;
UPDATE cyclists SET name="ROBEET Ludovic" WHERE cyclistId=235;
UPDATE cyclists SET name="THOMAS Benjamin" WHERE cyclistId=236;
UPDATE cyclists SET name="TOUMIRE Hugo" WHERE cyclistId=237;
UPDATE cyclists SET name="WOOD Harrison" WHERE cyclistId=238;
UPDATE cyclists SET name="GALL Felix" WHERE cyclistId=239;
UPDATE cyclists SET name="O CONNOR Ben" WHERE cyclistId=240;
UPDATE cyclists SET name="LAFAY Victor" WHERE cyclistId=241;
UPDATE cyclists SET name="BENNETT Sam" WHERE cyclistId=242;
UPDATE cyclists SET name="GODON Dorian" WHERE cyclistId=243;
UPDATE cyclists SET name="PARET-PEINTRE Aurélien" WHERE cyclistId=244;
UPDATE cyclists SET name="VENDRAME Andrea" WHERE cyclistId=245;
UPDATE cyclists SET name="BERTHET Clément" WHERE cyclistId=246;
UPDATE cyclists SET name="COSNEFROY Benoit" WHERE cyclistId=247;
UPDATE cyclists SET name="ARMIRAIL Bruno" WHERE cyclistId=248;
UPDATE cyclists SET name="PETERS 0s" WHERE cyclistId=249;
UPDATE cyclists SET name="BONNAMOUR Franck" WHERE cyclistId=250;
UPDATE cyclists SET name="BOUCHARD Geoffrey" WHERE cyclistId=251;
UPDATE cyclists SET name="DE BONDT Dries" WHERE cyclistId=252;
UPDATE cyclists SET name="DE PESTEL Sander" WHERE cyclistId=253;
UPDATE cyclists SET name="DEWULF Stan" WHERE cyclistId=254;
UPDATE cyclists SET name="GAUTHERAT Pierre" WHERE cyclistId=255;
UPDATE cyclists SET name="HANNINEN Jaako" WHERE cyclistId=256;
UPDATE cyclists SET name="LABROSSE Jordan" WHERE cyclistId=257;
UPDATE cyclists SET name="LAPEIRA Paul" WHERE cyclistId=258;
UPDATE cyclists SET name="NAESEN Oliver" WHERE cyclistId=259;
UPDATE cyclists SET name="POLLEFLIET Gianluca" WHERE cyclistId=260;
UPDATE cyclists SET name="PRODHOMME Nicolas" WHERE cyclistId=261;
UPDATE cyclists SET name="RETAILLEAU Valentin" WHERE cyclistId=262;
UPDATE cyclists SET name="TOUZE Damien" WHERE cyclistId=263;
UPDATE cyclists SET name="TRONCHON Bastien" WHERE cyclistId=264;
UPDATE cyclists SET name="WARBASSE Larry" WHERE cyclistId=265;
UPDATE cyclists SET name="PARET-PEINTRE Valentin" WHERE cyclistId=266;
UPDATE cyclists SET name="POWLESS Nelson" WHERE cyclistId=267;
UPDATE cyclists SET name="HEALY Ben" WHERE cyclistId=268;
UPDATE cyclists SET name="COSTA Rui" WHERE cyclistId=269;
UPDATE cyclists SET name="CARTHY Hugh" WHERE cyclistId=270;
UPDATE cyclists SET name="VAN DEN BERG Marijn" WHERE cyclistId=271;
UPDATE cyclists SET name="BETTIOL Alberto" WHERE cyclistId=272;
UPDATE cyclists SET name="CARAPAZ Richard" WHERE cyclistId=273;
UPDATE cyclists SET name="CEPEDA Jefferson" WHERE cyclistId=274;
UPDATE cyclists SET name="URAN Rigoberto" WHERE cyclistId=275;
UPDATE cyclists SET name="BISSEGGER Stefan" WHERE cyclistId=276;
UPDATE cyclists SET name="CARR SIMON" WHERE cyclistId=277;
UPDATE cyclists SET name="CHAVES Esteban" WHERE cyclistId=278;
UPDATE cyclists SET name="STEINHAUSER Georg" WHERE cyclistId=279;
UPDATE cyclists SET name="AMADOR Andrey" WHERE cyclistId=280;
UPDATE cyclists SET name="BELOKI Markel" WHERE cyclistId=281;
UPDATE cyclists SET name="DE BOD Stefan" WHERE cyclistId=282;
UPDATE cyclists SET name="NERURKAR Lukas" WHERE cyclistId=283;
UPDATE cyclists SET name="PADUN Mark" WHERE cyclistId=284;
UPDATE cyclists SET name="PICCOLO Andrea" WHERE cyclistId=285;
UPDATE cyclists SET name="RAFFERTY Darren" WHERE cyclistId=286;
UPDATE cyclists SET name="ROOTKIN-GRAY Jack" WHERE cyclistId=287;
UPDATE cyclists SET name="RUTSCH Jonas" WHERE cyclistId=288;
UPDATE cyclists SET name="RYAN Archie" WHERE cyclistId=289;
UPDATE cyclists SET name="SWEENY Harry" WHERE cyclistId=290;
UPDATE cyclists SET name="TODOME Yuhi" WHERE cyclistId=291;
UPDATE cyclists SET name="VALGREN Michael" WHERE cyclistId=292;
UPDATE cyclists SET name="VAN DER LEE Jardi Christiaan" WHERE cyclistId=293;
UPDATE cyclists SET name="HONORE Mikkel Frolich" WHERE cyclistId=294;
UPDATE cyclists SET name="AGIRRE Jon" WHERE cyclistId=295;
UPDATE cyclists SET name="AZNAR Hugo" WHERE cyclistId=296;
UPDATE cyclists SET name="AZNAR Unai" WHERE cyclistId=297;
UPDATE cyclists SET name="BERRADE Urko" WHERE cyclistId=298;
UPDATE cyclists SET name="BRUSTENGA Marc" WHERE cyclistId=299;
UPDATE cyclists SET name="CASTRILLO Pablo" WHERE cyclistId=300;
UPDATE cyclists SET name="COBO Ivan" WHERE cyclistId=301;
UPDATE cyclists SET name="ELOSEGUI Inigo" WHERE cyclistId=302;
UPDATE cyclists SET name="FER0DEZ Miguel Angel" WHERE cyclistId=303;
UPDATE cyclists SET name="GALVAN Francisco" WHERE cyclistId=304;
UPDATE cyclists SET name="GARCIA PIERNA Carlos" WHERE cyclistId=305;
UPDATE cyclists SET name="GUTIERREZ Jorge" WHERE cyclistId=306;
UPDATE cyclists SET name="IRIBAR Unai" WHERE cyclistId=307;
UPDATE cyclists SET name="JAIME Alex" WHERE cyclistId=308;
UPDATE cyclists SET name="LOPEZ Jordi" WHERE cyclistId=309;
UPDATE cyclists SET name="MARQUEZ Marti" WHERE cyclistId=310;
UPDATE cyclists SET name="MIQUEL Pau" WHERE cyclistId=311;
UPDATE cyclists SET name="PARRA José Félix" WHERE cyclistId=312;
UPDATE cyclists SET name="RETEGI Mikel" WHERE cyclistId=313;
UPDATE cyclists SET name="RUIZ Ibon" WHERE cyclistId=314;
UPDATE cyclists SET name="SANCHEZ Eugenio" WHERE cyclistId=315;
UPDATE cyclists SET name="SOTO Antonio Jesus" WHERE cyclistId=316;
UPDATE cyclists SET name="URIARTE Diego" WHERE cyclistId=317;
UPDATE cyclists SET name="VAN DER TUUK Danny" WHERE cyclistId=318;
UPDATE cyclists SET name="ABERASTURI Jon" WHERE cyclistId=319;
UPDATE cyclists SET name="ALUSTIZA Nicolas" WHERE cyclistId=320;
UPDATE cyclists SET name="AZPARREN Enekoitz" WHERE cyclistId=321;
UPDATE cyclists SET name="AZURMENDI Ibai" WHERE cyclistId=322;
UPDATE cyclists SET name="BERASATEGI Xabier" WHERE cyclistId=323;
UPDATE cyclists SET name="BIZKARRA Mikel" WHERE cyclistId=324;
UPDATE cyclists SET name="BONILLO Iker" WHERE cyclistId=325;
UPDATE cyclists SET name="BOU Joan" WHERE cyclistId=326;
UPDATE cyclists SET name="CANELLAS Xavier" WHERE cyclistId=327;
UPDATE cyclists SET name="CUADRADO Unai" WHERE cyclistId=328;
UPDATE cyclists SET name="DE LA PARTE Víctor" WHERE cyclistId=329;
UPDATE cyclists SET name="ETXEBERRIA Asier" WHERE cyclistId=330;
UPDATE cyclists SET name="ISASA Xabier" WHERE cyclistId=331;
UPDATE cyclists SET name="ITURRIA Mikel" WHERE cyclistId=332;
UPDATE cyclists SET name="JUARISTI Txomin" WHERE cyclistId=333;
UPDATE cyclists SET name="LOPEZ DE ABETXUKO Andoni" WHERE cyclistId=334;
UPDATE cyclists SET name="MARTIN Gotzon" WHERE cyclistId=335;
UPDATE cyclists SET name="MATÉ Luis Ángel" WHERE cyclistId=336;
UPDATE cyclists SET name="MINTEGUI Iker" WHERE cyclistId=337;
UPDATE cyclists SET name="ZUBELDIA Unai" WHERE cyclistId=338;
UPDATE cyclists SET name="KUNG Stefan" WHERE cyclistId=339;
UPDATE cyclists SET name="MADOUAS Valentin" WHERE cyclistId=340;
UPDATE cyclists SET name="GAUDU David" WHERE cyclistId=341;
UPDATE cyclists SET name="GREGOIRE Romain" WHERE cyclistId=342;
UPDATE cyclists SET name="MARTINEZ Lenny" WHERE cyclistId=343;
UPDATE cyclists SET name="PENHEOT Paul" WHERE cyclistId=344;
UPDATE cyclists SET name="MOLARD Rudy" WHERE cyclistId=345;
UPDATE cyclists SET name="PITHIE Laurence" WHERE cyclistId=346;
UPDATE cyclists SET name="ASKEY Lewis" WHERE cyclistId=347;
UPDATE cyclists SET name="BYSTRÖM Sven Erik" WHERE cyclistId=348;
UPDATE cyclists SET name="ROCHAS Rémy" WHERE cyclistId=349;
UPDATE cyclists SET name="GENIETS Kévin" WHERE cyclistId=350;
UPDATE cyclists SET name="WATSON Samuel" WHERE cyclistId=351;
UPDATE cyclists SET name="BARTHE Cyril" WHERE cyclistId=352;
UPDATE cyclists SET name="DAVY Clément" WHERE cyclistId=353;
UPDATE cyclists SET name="GERMANI Lorenzo" WHERE cyclistId=354;
UPDATE cyclists SET name="KONOVALOVAS Ignatas" WHERE cyclistId=355;
UPDATE cyclists SET name="LE GAC Olivier" WHERE cyclistId=356;
UPDATE cyclists SET name="LE HUITOUZE Eddy" WHERE cyclistId=357;
UPDATE cyclists SET name="LIENHARD Fabian" WHERE cyclistId=358;
UPDATE cyclists SET name="PACHER Quentin" WHERE cyclistId=359;
UPDATE cyclists SET name="PALENI Enzo" WHERE cyclistId=360;
UPDATE cyclists SET name="RUSSO Clément" WHERE cyclistId=361;
UPDATE cyclists SET name="SARREAU Marc" WHERE cyclistId=362;
UPDATE cyclists SET name="THOMPSON Reuben" WHERE cyclistId=363;
UPDATE cyclists SET name="VAN DEN BERG Lars" WHERE cyclistId=364;
UPDATE cyclists SET name="WALLS Matthew" WHERE cyclistId=365;
UPDATE cyclists SET name="GANNA FIlippo" WHERE cyclistId=366;
UPDATE cyclists SET name="PIDCOCK Thomas" WHERE cyclistId=367;
UPDATE cyclists SET name="THOMAS Geraint" WHERE cyclistId=368;
UPDATE cyclists SET name="RODRIGUEZ Carlos" WHERE cyclistId=369;
UPDATE cyclists SET name="SHEFFIELD Magnus" WHERE cyclistId=370;
UPDATE cyclists SET name="KWIATKOWSKI Michal" WHERE cyclistId=371;
UPDATE cyclists SET name="ARENSMANN Thymen" WHERE cyclistId=372;
UPDATE cyclists SET name="HAYTER Ethan" WHERE cyclistId=373;
UPDATE cyclists SET name="TARLING Joshua" WHERE cyclistId=374;
UPDATE cyclists SET name="VIVIANI Elia" WHERE cyclistId=375;
UPDATE cyclists SET name="CASTROVIEJO Jonathan" WHERE cyclistId=376;
UPDATE cyclists SET name="FOSS Tobias" WHERE cyclistId=377;
UPDATE cyclists SET name="NARVAEZ Jhonathan" WHERE cyclistId=378;
UPDATE cyclists SET name="BERNAL Egan" WHERE cyclistId=379;
UPDATE cyclists SET name="DE PLUS Laurens" WHERE cyclistId=380;
UPDATE cyclists SET name="RODRIGUEZ Oscar" WHERE cyclistId=381;
UPDATE cyclists SET name="TURNER Ben" WHERE cyclistId=382;
UPDATE cyclists SET name="AUGUST Andrew" WHERE cyclistId=383;
UPDATE cyclists SET name="FRAILE Omar" WHERE cyclistId=384;
UPDATE cyclists SET name="HAYTER Leo" WHERE cyclistId=385;
UPDATE cyclists SET name="HEIDUK Kim" WHERE cyclistId=386;
UPDATE cyclists SET name="LEONARD Michael" WHERE cyclistId=387;
UPDATE cyclists SET name="PUCCIO Salvatore" WHERE cyclistId=388;
UPDATE cyclists SET name="RIVERA Brandon" WHERE cyclistId=389;
UPDATE cyclists SET name="ROWE Luke" WHERE cyclistId=390;
UPDATE cyclists SET name="STORM Theodor" WHERE cyclistId=391;
UPDATE cyclists SET name="SWIFT Ben" WHERE cyclistId=392;
UPDATE cyclists SET name="SWIFT Connor" WHERE cyclistId=393;
UPDATE cyclists SET name="THIJSSEN Gerben" WHERE cyclistId=394;
UPDATE cyclists SET name="ROTA Lorenzo" WHERE cyclistId=395;
UPDATE cyclists SET name="ZIMMERMANN Georg" WHERE cyclistId=396;
UPDATE cyclists SET name="TEUNISSEN Mike" WHERE cyclistId=397;
UPDATE cyclists SET name="GIRMAY Biniam" WHERE cyclistId=398;
UPDATE cyclists SET name="PAGE Hugo" WHERE cyclistId=399;
UPDATE cyclists SET name="GOOSSENS Kobe" WHERE cyclistId=400;
UPDATE cyclists SET name="BUSATTO Francesco" WHERE cyclistId=401;
UPDATE cyclists SET name="MARIT Arne" WHERE cyclistId=402;
UPDATE cyclists SET name="MEINTJES Louis" WHERE cyclistId=403;
UPDATE cyclists SET name="HERREGODTS Rune" WHERE cyclistId=404;
UPDATE cyclists SET name="REX Laurenz" WHERE cyclistId=405;
UPDATE cyclists SET name="BRAET Vito" WHERE cyclistId=406;
UPDATE cyclists SET name="CALMEJANE Lilian" WHERE cyclistId=407;
UPDATE cyclists SET name="COLLEONI Kevin" WHERE cyclistId=408;
UPDATE cyclists SET name="DE POOTER Dries" WHERE cyclistId=409;
UPDATE cyclists SET name="FAURE PROST Alexy" WHERE cyclistId=410;
UPDATE cyclists SET name="MIHKELS Madis" WHERE cyclistId=411;
UPDATE cyclists SET name="PAQUOT Tom" WHERE cyclistId=412;
UPDATE cyclists SET name="PETILI Simone" WHERE cyclistId=413;
UPDATE cyclists SET name="PETIT Adrien" WHERE cyclistId=414;
UPDATE cyclists SET name="PLANCKAERT Baptiste" WHERE cyclistId=415;
UPDATE cyclists SET name="SMITH Dion" WHERE cyclistId=416;
UPDATE cyclists SET name="TAARAMAE Rein" WHERE cyclistId=417;
UPDATE cyclists SET name="VAN DER HOORN Taco" WHERE cyclistId=418;
UPDATE cyclists SET name="VAN POPPEL Boy" WHERE cyclistId=419;
UPDATE cyclists SET name="VAN SINTMAARTENSDIJK Roel" WHERE cyclistId=420;
UPDATE cyclists SET name="WOODS Michael" WHERE cyclistId=421;
UPDATE cyclists SET name="GEE Derek" WHERE cyclistId=422;
UPDATE cyclists SET name="STRONG Corbin" WHERE cyclistId=423;
UPDATE cyclists SET name="ACKERMANN Pascal" WHERE cyclistId=424;
UPDATE cyclists SET name="CLARKE Simon" WHERE cyclistId=425;
UPDATE cyclists SET name="TEUNS Dylan" WHERE cyclistId=426;
UPDATE cyclists SET name="VERNON Ethan" WHERE cyclistId=427;
UPDATE cyclists SET name="BENNETT Geroge" WHERE cyclistId=428;
UPDATE cyclists SET name="EINHORN Itamar" WHERE cyclistId=429;
UPDATE cyclists SET name="HOFFSTETTER Hugo" WHERE cyclistId=430;
UPDATE cyclists SET name="WILLIAMS Stephen" WHERE cyclistId=431;
UPDATE cyclists SET name="NEILANDS Krists" WHERE cyclistId=432;
UPDATE cyclists SET name="SHEEHAN Riley" WHERE cyclistId=433;
UPDATE cyclists SET name="VAN ASBROECK Tom" WHERE cyclistId=434;
UPDATE cyclists SET name="BOIVIN Guillaume" WHERE cyclistId=435;
UPDATE cyclists SET name="FRIGO Marco" WHERE cyclistId=436;
UPDATE cyclists SET name="FROOME Chris" WHERE cyclistId=437;
UPDATE cyclists SET name="HOLLYMAN Mason" WHERE cyclistId=438;
UPDATE cyclists SET name="HOULE Hugo" WHERE cyclistId=439;
UPDATE cyclists SET name="KOGUT Oded" WHERE cyclistId=440;
UPDATE cyclists SET name="PICKRELL Riley" WHERE cyclistId=441;
UPDATE cyclists SET name="RAISBERG Nadav" WHERE cyclistId=442;
UPDATE cyclists SET name="RICCITELLO Matthew" WHERE cyclistId=443;
UPDATE cyclists SET name="SAGIV Guy" WHERE cyclistId=444;
UPDATE cyclists SET name="SCHULTZ Nick" WHERE cyclistId=445;
UPDATE cyclists SET name="SCHWARZMANN Michael" WHERE cyclistId=446;
UPDATE cyclists SET name="STEWART Jake" WHERE cyclistId=447;
UPDATE cyclists SET name="WURTZ SCHMIDT Mads" WHERE cyclistId=448;
UPDATE cyclists SET name="ZABEL Rick" WHERE cyclistId=449;
UPDATE cyclists SET name="FUGLSANG Jakob" WHERE cyclistId=450;
UPDATE cyclists SET name="PEDERSEN Mads" WHERE cyclistId=451;
UPDATE cyclists SET name="SJKELMOSE Mattias" WHERE cyclistId=452;
UPDATE cyclists SET name="BAGIOLI Andrea" WHERE cyclistId=453;
UPDATE cyclists SET name="CICCONE Guilio" WHERE cyclistId=454;
UPDATE cyclists SET name="SKUJINS Toms" WHERE cyclistId=455;
UPDATE cyclists SET name="GEOGHEGAN HART Tao" WHERE cyclistId=456;
UPDATE cyclists SET name="MILAN Jonathan" WHERE cyclistId=457;
UPDATE cyclists SET name="STUYVEN Jasper" WHERE cyclistId=458;
UPDATE cyclists SET name="KONRAD Patrick" WHERE cyclistId=459;
UPDATE cyclists SET name="THEUNS Edward" WHERE cyclistId=460;
UPDATE cyclists SET name="TESFASTION Nathanel" WHERE cyclistId=461;
UPDATE cyclists SET name="KIRSCH Alex" WHERE cyclistId=462;
UPDATE cyclists SET name="NYS Thibau" WHERE cyclistId=463;
UPDATE cyclists SET name="VACEK Matthias" WHERE cyclistId=464;
UPDATE cyclists SET name="CONSONNI Simone" WHERE cyclistId=465;
UPDATE cyclists SET name="MOLLEMA Bauke" WHERE cyclistId=466;
UPDATE cyclists SET name="SIMMONS Quinn" WHERE cyclistId=467;
UPDATE cyclists SET name="BERNARD Julien" WHERE cyclistId=468;
UPDATE cyclists SET name="CATALDO Dario" WHERE cyclistId=469;
UPDATE cyclists SET name="DECLERCQ Tim" WHERE cyclistId=470;
UPDATE cyclists SET name="FELLINE Fabio" WHERE cyclistId=471;
UPDATE cyclists SET name="GIBBONS Ryan" WHERE cyclistId=472;
UPDATE cyclists SET name="HOOLE Dan" WHERE cyclistId=473;
UPDATE cyclists SET name="LOPEZ Juan Pedro" WHERE cyclistId=474;
UPDATE cyclists SET name="MOSCA Jacopo" WHERE cyclistId=475;
UPDATE cyclists SET name="OOMEN Sam" WHERE cyclistId=476;
UPDATE cyclists SET name="VERGAERDE Otto" WHERE cyclistId=477;
UPDATE cyclists SET name="VERONA Carlos" WHERE cyclistId=478;
UPDATE cyclists SET name="DE LIE Arnaud" WHERE cyclistId=479;
UPDATE cyclists SET name="VERMEERSCH Florian" WHERE cyclistId=480;
UPDATE cyclists SET name="KRON Andreas" WHERE cyclistId=481;
UPDATE cyclists SET name="VAN GILS Maxim" WHERE cyclistId=482;
UPDATE cyclists SET name="MENTEN Milan" WHERE cyclistId=483;
UPDATE cyclists SET name="DE BUYST Jasper" WHERE cyclistId=484;
UPDATE cyclists SET name="VAN EETVELT Lennert" WHERE cyclistId=485;
UPDATE cyclists SET name="SEPÚLVEDA Eduardo" WHERE cyclistId=486;
UPDATE cyclists SET name="VAN MOER Brent" WHERE cyclistId=487;
UPDATE cyclists SET name="TAMINIAUX Lionel" WHERE cyclistId=488;
UPDATE cyclists SET name="BEULLENS Cedric" WHERE cyclistId=489;
UPDATE cyclists SET name="EENKHOORN Pascal" WHERE cyclistId=490;
UPDATE cyclists SET name="SEGAERT Alec" WHERE cyclistId=491;
UPDATE cyclists SET name="VAN DE PAAR Jarne" WHERE cyclistId=492;
UPDATE cyclists SET name="ADAMIETZ Johannes" WHERE cyclistId=493;
UPDATE cyclists SET name="BERCKMOES Jenno" WHERE cyclistId=494;
UPDATE cyclists SET name="CAMPENAERTS Victor" WHERE cyclistId=495;
UPDATE cyclists SET name="CURRIE Logan" WHERE cyclistId=496;
UPDATE cyclists SET name="DE GENDT Thomas" WHERE cyclistId=497;
UPDATE cyclists SET name="DRIZNERS Jarrad" WHERE cyclistId=498;
UPDATE cyclists SET name="GREEGARD Jonas" WHERE cyclistId=499;
UPDATE cyclists SET name="GRIGNARD Sébastien" WHERE cyclistId=500;
UPDATE cyclists SET name="GUARNIERI Jacopo" WHERE cyclistId=501;
UPDATE cyclists SET name="LIVYNS Arjen" WHERE cyclistId=502;
UPDATE cyclists SET name="MONIQUET Sylvain" WHERE cyclistId=503;
UPDATE cyclists SET name="PAASSCHENS Mathijs" WHERE cyclistId=504;
UPDATE cyclists SET name="SLOCK Liam" WHERE cyclistId=505;
UPDATE cyclists SET name="TAMINIAUX Lionel" WHERE cyclistId=506;
UPDATE cyclists SET name="VANDENABEELE Henri" WHERE cyclistId=507;
UPDATE cyclists SET name="VANHOUCKE Harm" WHERE cyclistId=508;
UPDATE cyclists SET name="ARANBURU Alex" WHERE cyclistId=509;
UPDATE cyclists SET name="MAS Enric" WHERE cyclistId=510;
UPDATE cyclists SET name="RUBIO Einer" WHERE cyclistId=511;
UPDATE cyclists SET name="FORMOLO Davide" WHERE cyclistId=512;
UPDATE cyclists SET name="GARCIA CORTINA Ivan" WHERE cyclistId=513;
UPDATE cyclists SET name="LAZKANO Oier" WHERE cyclistId=514;
UPDATE cyclists SET name="CAVAGNA Rémi" WHERE cyclistId=515;
UPDATE cyclists SET name="QUINTANA Nairo" WHERE cyclistId=516;
UPDATE cyclists SET name="GAVIRIA Fer0do" WHERE cyclistId=517;
UPDATE cyclists SET name="GUERREIRO Ruben" WHERE cyclistId=518;
UPDATE cyclists SET name="SOSA Ivan" WHERE cyclistId=519;
UPDATE cyclists SET name="SANCHEZ Pelayo" WHERE cyclistId=520;
UPDATE cyclists SET name="SERRANO Gonzalo" WHERE cyclistId=521;
UPDATE cyclists SET name="MILESI Lorenzo" WHERE cyclistId=522;
UPDATE cyclists SET name="MULHBERGER Gregor" WHERE cyclistId=523;
UPDATE cyclists SET name="OLIVEIRA Nelson" WHERE cyclistId=524;
UPDATE cyclists SET name="ARCAS Jorge" WHERE cyclistId=525;
UPDATE cyclists SET name="BARRENETXEA Jon" WHERE cyclistId=526;
UPDATE cyclists SET name="BARTA Will" WHERE cyclistId=527;
UPDATE cyclists SET name="CANAL Carlos" WHERE cyclistId=528;
UPDATE cyclists SET name="CIMOLAI Davide" WHERE cyclistId=529;
UPDATE cyclists SET name="JACOBS Johan" WHERE cyclistId=530;
UPDATE cyclists SET name="MORO Manlio" WHERE cyclistId=531;
UPDATE cyclists SET name="NORSGAARD JORGENSEN Mathias" WHERE cyclistId=532;
UPDATE cyclists SET name="PEDRERO Antonio" WHERE cyclistId=533;
UPDATE cyclists SET name="RANGEL Vinicius" WHERE cyclistId=534;
UPDATE cyclists SET name="ROMEO Ivan" WHERE cyclistId=535;
UPDATE cyclists SET name="ROMO Javier" WHERE cyclistId=536;
UPDATE cyclists SET name="SAMITIER Sergio" WHERE cyclistId=537;
UPDATE cyclists SET name="TORRES Albert" WHERE cyclistId=538;
UPDATE cyclists SET name="DONOVAN Mark" WHERE cyclistId=539;
UPDATE cyclists SET name="MOSCHETTI Matteo" WHERE cyclistId=540;
UPDATE cyclists SET name="FRISON Frederik" WHERE cyclistId=541;
UPDATE cyclists SET name="HOWSON Damien" WHERE cyclistId=542;
UPDATE cyclists SET name="TOWNSEND Rory" WHERE cyclistId=543;
UPDATE cyclists SET name="ABREHA Negasi Haylu" WHERE cyclistId=544;
UPDATE cyclists SET name="AZPARREN Xabier Mikel" WHERE cyclistId=545;
UPDATE cyclists SET name="BRAMBILLA Gianluca" WHERE cyclistId=546;
UPDATE cyclists SET name="CALZONI Walter" WHERE cyclistId=547;
UPDATE cyclists SET name="CAMPRUBI Marcel" WHERE cyclistId=548;
UPDATE cyclists SET name="CHRISTEN Fabio" WHERE cyclistId=549;
UPDATE cyclists SET name="COLOMBO Filippo" WHERE cyclistId=550;
UPDATE cyclists SET name="CONCA Filippo" WHERE cyclistId=551;
UPDATE cyclists SET name="DE LA CRUZ David" WHERE cyclistId=552;
UPDATE cyclists SET name="DEVRIENDT Tom" WHERE cyclistId=553;
UPDATE cyclists SET name="FANCELLU Alessandro" WHERE cyclistId=554;
UPDATE cyclists SET name="HAGEN Carl Fredrik" WHERE cyclistId=555;
UPDATE cyclists SET name="LUDVIGSSON Tobias" WHERE cyclistId=556;
UPDATE cyclists SET name="MALECKI Kamil" WHERE cyclistId=557;
UPDATE cyclists SET name="MONK Cyrus" WHERE cyclistId=558;
UPDATE cyclists SET name="NIZZOLO Giacomo" WHERE cyclistId=559;
UPDATE cyclists SET name="PARISINI Nicolo" WHERE cyclistId=560;
UPDATE cyclists SET name="ROSSKOPF Joey" WHERE cyclistId=561;
UPDATE cyclists SET name="SAJNOK Szymon" WHERE cyclistId=562;
UPDATE cyclists SET name="STEIMLE Jannik" WHERE cyclistId=563;
UPDATE cyclists SET name="WHELAN James" WHERE cyclistId=564;
UPDATE cyclists SET name="ZUKOWSKY Nickolas" WHERE cyclistId=565;
UPDATE cyclists SET name="BADILATTI Matteo" WHERE cyclistId=566;
UPDATE cyclists SET name="EVENEPOEL Remco" WHERE cyclistId=567;
UPDATE cyclists SET name="LANDA Mikel" WHERE cyclistId=568;
UPDATE cyclists SET name="MERLIER Tim" WHERE cyclistId=569;
UPDATE cyclists SET name="VAN WILDER Ilan" WHERE cyclistId=570;
UPDATE cyclists SET name="LAMPAERT Yves" WHERE cyclistId=571;
UPDATE cyclists SET name="ALAPHILIPPE Julian" WHERE cyclistId=572;
UPDATE cyclists SET name="ASGREEN Kasper" WHERE cyclistId=573;
UPDATE cyclists SET name="CATTANEO Mattia" WHERE cyclistId=574;
UPDATE cyclists SET name="PEDERSEN Casper" WHERE cyclistId=575;
UPDATE cyclists SET name="BASTIAENS Ayco" WHERE cyclistId=576;
UPDATE cyclists SET name="CERNY Josef" WHERE cyclistId=577;
UPDATE cyclists SET name="GELDERS Gil" WHERE cyclistId=578;
UPDATE cyclists SET name="HIRT Jan" WHERE cyclistId=579;
UPDATE cyclists SET name="HUBY Antoine" WHERE cyclistId=580;
UPDATE cyclists SET name="KNOX James" WHERE cyclistId=581;
UPDATE cyclists SET name="LAMPERTI Luke" WHERE cyclistId=582;
UPDATE cyclists SET name="LECERF William Junior" WHERE cyclistId=583;
UPDATE cyclists SET name="MAGNIER Paul" WHERE cyclistId=584;
UPDATE cyclists SET name="MASNADA Fausto" WHERE cyclistId=585;
UPDATE cyclists SET name="MOSCON Gianni" WHERE cyclistId=586;
UPDATE cyclists SET name="SERRY Pieter" WHERE cyclistId=587;
UPDATE cyclists SET name="SVRCEK Martin" WHERE cyclistId=588;
UPDATE cyclists SET name="VAN LERBERGHE Bert" WHERE cyclistId=589;
UPDATE cyclists SET name="VANGHELUWE Warre" WHERE cyclistId=590;
UPDATE cyclists SET name="VANSEVE0T Mauri" WHERE cyclistId=591;
UPDATE cyclists SET name="VERVAEKE Louis" WHERE cyclistId=592;
UPDATE cyclists SET name="WARLOP Jordi" WHERE cyclistId=593;
UPDATE cyclists SET name="BLOEM Joren" WHERE cyclistId=594;
UPDATE cyclists SET name="BOMBOI Davide" WHERE cyclistId=595;
UPDATE cyclists SET name="BOUTS Jordy" WHERE cyclistId=596;
UPDATE cyclists SET name="BUDDING Martijn" WHERE cyclistId=597;
UPDATE cyclists SET name="CHRISTOPHERSEN Cedrik Bakke" WHERE cyclistId=598;
UPDATE cyclists SET name="DE VRIES Hartthijs" WHERE cyclistId=599;
UPDATE cyclists SET name="GELEIJN Owen" WHERE cyclistId=600;
UPDATE cyclists SET name="HUENS Axel" WHERE cyclistId=601;
UPDATE cyclists SET name="HUYET Baptiste" WHERE cyclistId=602;
UPDATE cyclists SET name="JOHANNINK Jelle" WHERE cyclistId=603;
UPDATE cyclists SET name="KOPECKÝ Tomáš" WHERE cyclistId=604;
UPDATE cyclists SET name="KYFFIN Zeb" WHERE cyclistId=605;
UPDATE cyclists SET name="LOOCKX Lander" WHERE cyclistId=606;
UPDATE cyclists SET name="MAIRE Adrien" WHERE cyclistId=607;
UPDATE cyclists SET name="NIELSEN Sebastian" WHERE cyclistId=608;
UPDATE cyclists SET name="PAIGE Charles" WHERE cyclistId=609;
UPDATE cyclists SET name="PEDERSEN Nicklas Amdi" WHERE cyclistId=610;
UPDATE cyclists SET name="STOCKMAN Abram" WHERE cyclistId=611;
UPDATE cyclists SET name="STOKBRO Andreas" WHERE cyclistId=612;
UPDATE cyclists SET name="ŤOUPALÍK Adam" WHERE cyclistId=613;
UPDATE cyclists SET name="STEWART Mark" WHERE cyclistId=614;
UPDATE cyclists SET name="MARECZKO Jakub" WHERE cyclistId=615;
UPDATE cyclists SET name="AMELLA Matteo" WHERE cyclistId=616;
UPDATE cyclists SET name="BALDACCINI Davide" WHERE cyclistId=617;
UPDATE cyclists SET name="BONIFAZIO Niccolo" WHERE cyclistId=618;
UPDATE cyclists SET name="CONTI Valerio" WHERE cyclistId=619;
UPDATE cyclists SET name="DARBELLAY Valentin" WHERE cyclistId=620;
UPDATE cyclists SET name="DEBONS Antoine" WHERE cyclistId=621;
UPDATE cyclists SET name="IACCHI Alessandro" WHERE cyclistId=622;
UPDATE cyclists SET name="MASOTTO Giulio" WHERE cyclistId=623;
UPDATE cyclists SET name="MONACO Alessandro" WHERE cyclistId=624;
UPDATE cyclists SET name="MURGANO Marco" WHERE cyclistId=625;
UPDATE cyclists SET name="OLIVERO Simone" WHERE cyclistId=626;
UPDATE cyclists SET name="PADUN Mark" WHERE cyclistId=627;
UPDATE cyclists SET name="PONOMAR Andrii" WHERE cyclistId=628;
UPDATE cyclists SET name="QUARTUCCI Lorenzo" WHERE cyclistId=629;
UPDATE cyclists SET name="SBARAGLI Kristian" WHERE cyclistId=630;
UPDATE cyclists SET name="STÖCKLI Jan" WHERE cyclistId=631;
UPDATE cyclists SET name="TSARENKO Kyrylo" WHERE cyclistId=632;
UPDATE cyclists SET name="VAN EMPEL Etienne" WHERE cyclistId=633;
UPDATE cyclists SET name="ZAMBELLI Samuele" WHERE cyclistId=634;
UPDATE cyclists SET name="BARDET Romain" WHERE cyclistId=635;
UPDATE cyclists SET name="BARGUIL Warren" WHERE cyclistId=636;
UPDATE cyclists SET name="JAKOBSEN Fabio" WHERE cyclistId=637;
UPDATE cyclists SET name="POOLE Max" WHERE cyclistId=638;
UPDATE cyclists SET name="DEGENKOLB John" WHERE cyclistId=639;
UPDATE cyclists SET name="DINHAM Matthew" WHERE cyclistId=640;
UPDATE cyclists SET name="VERMAERKE Kevin" WHERE cyclistId=641;
UPDATE cyclists SET name="EEKHOFF Nils" WHERE cyclistId=642;
UPDATE cyclists SET name="ONLEY Oscar" WHERE cyclistId=643;
UPDATE cyclists SET name="ANDRESEN Tobias Lund" WHERE cyclistId=644;
UPDATE cyclists SET name="BEVIN Patrick" WHERE cyclistId=645;
UPDATE cyclists SET name="BITTNER Pavel" WHERE cyclistId=646;
UPDATE cyclists SET name="COMBAUD Romain" WHERE cyclistId=647;
UPDATE cyclists SET name="EDDY Patrick" WHERE cyclistId=648;
UPDATE cyclists SET name="EDMONDSON Alexander" WHERE cyclistId=649;
UPDATE cyclists SET name="FLYNN Sean" WHERE cyclistId=650;
UPDATE cyclists SET name="HAMILTON Chris" WHERE cyclistId=651;
UPDATE cyclists SET name="LEEMREIZE Gijs" WHERE cyclistId=652;
UPDATE cyclists SET name="LEIJNSE Enzo" WHERE cyclistId=653;
UPDATE cyclists SET name="LIEPINS Emils" WHERE cyclistId=654;
UPDATE cyclists SET name="MARKL Niklas" WHERE cyclistId=655;
UPDATE cyclists SET name="NABERMAN Tim" WHERE cyclistId=656;
UPDATE cyclists SET name="ROOSEN Timo" WHERE cyclistId=657;
UPDATE cyclists SET name="TUSVELD Martijn" WHERE cyclistId=658;
UPDATE cyclists SET name="VAN DEN BERG Julius" WHERE cyclistId=659;
UPDATE cyclists SET name="VAN DEN BROEK Frank" WHERE cyclistId=660;
UPDATE cyclists SET name="VAN UDEN Casper" WHERE cyclistId=661;
UPDATE cyclists SET name="WELTEN Bram" WHERE cyclistId=662;
UPDATE cyclists SET name="CLAEYS Arno" WHERE cyclistId=663;
UPDATE cyclists SET name="CLYNHENS Toon" WHERE cyclistId=664;
UPDATE cyclists SET name="CRAPS Lars" WHERE cyclistId=665;
UPDATE cyclists SET name="DE WILDE Gilles" WHERE cyclistId=666;
UPDATE cyclists SET name="DEJAEGHER Jasper" WHERE cyclistId=667;
UPDATE cyclists SET name="DEWEIRDT Siebe" WHERE cyclistId=668;
UPDATE cyclists SET name="GERITS Vince" WHERE cyclistId=669;
UPDATE cyclists SET name="MARIS Elias" WHERE cyclistId=670;
UPDATE cyclists SET name="VAN HEMELEN Vincent" WHERE cyclistId=671;
UPDATE cyclists SET name="VANDENBRANDEN Noah" WHERE cyclistId=672;
UPDATE cyclists SET name="VANDENSTORME Dylan" WHERE cyclistId=673;
UPDATE cyclists SET name="VANDEVELDE Yentl" WHERE cyclistId=674;
UPDATE cyclists SET name="VANHOOF Ward" WHERE cyclistId=675;
UPDATE cyclists SET name="VERCOUILLIE Victor" WHERE cyclistId=676;
UPDATE cyclists SET name="BONNEU Kamiel" WHERE cyclistId=677;
UPDATE cyclists SET name="DE VYLDER Lindsay" WHERE cyclistId=678;
UPDATE cyclists SET name="DENS Tuur" WHERE cyclistId=679;
UPDATE cyclists SET name="HESTERS Jules" WHERE cyclistId=680;
UPDATE cyclists SET name="VAN POUCKE Aaron" WHERE cyclistId=681;
UPDATE cyclists SET name="COLMAN Alex" WHERE cyclistId=682;
UPDATE cyclists SET name="YATES Simon" WHERE cyclistId=683;
UPDATE cyclists SET name="MATTHEWS Michael" WHERE cyclistId=684;
UPDATE cyclists SET name="GRONEWEGEN Dylan" WHERE cyclistId=685;
UPDATE cyclists SET name="EWAN Caleb" WHERE cyclistId=686;
UPDATE cyclists SET name="SCHMID Mauro" WHERE cyclistId=687;
UPDATE cyclists SET name="ZANA FIlippo" WHERE cyclistId=688;
UPDATE cyclists SET name="DUNBAR Eddie" WHERE cyclistId=689;
UPDATE cyclists SET name="ENGELHARDT Felix" WHERE cyclistId=690;
UPDATE cyclists SET name="WALSCHEID Max" WHERE cyclistId=691;
UPDATE cyclists SET name="PLAPP Luke" WHERE cyclistId=692;
UPDATE cyclists SET name="HARPER Chris" WHERE cyclistId=693;
UPDATE cyclists SET name="MEZGEC Luka" WHERE cyclistId=694;
UPDATE cyclists SET name="BERHE Welay Hagos" WHERE cyclistId=695;
UPDATE cyclists SET name="CRADDOCK Lawson" WHERE cyclistId=696;
UPDATE cyclists SET name="DE MARCHI Alessandro" WHERE cyclistId=697;
UPDATE cyclists SET name="DE PRETTO Davide" WHERE cyclistId=698;
UPDATE cyclists SET name="DURBRIDGE Luke" WHERE cyclistId=699;
UPDATE cyclists SET name="FOLDAGER Anders" WHERE cyclistId=700;
UPDATE cyclists SET name="HAMILTON Lucas" WHERE cyclistId=701;
UPDATE cyclists SET name="HEPBURN Michael" WHERE cyclistId=702;
UPDATE cyclists SET name="JANSEN Amund Grondhal" WHERE cyclistId=703;
UPDATE cyclists SET name="JUUL-JENSEN Christopher" WHERE cyclistId=704;
UPDATE cyclists SET name="MAAS Jan" WHERE cyclistId=705;
UPDATE cyclists SET name="O BRIEN Kelland" WHERE cyclistId=706;
UPDATE cyclists SET name="PEÑA Jesús David" WHERE cyclistId=707;
UPDATE cyclists SET name="PORTER Rudy" WHERE cyclistId=708;
UPDATE cyclists SET name="QUICK Blake" WHERE cyclistId=709;
UPDATE cyclists SET name="REINDERS Elmar" WHERE cyclistId=710;
UPDATE cyclists SET name="SCOTSON Callum" WHERE cyclistId=711;
UPDATE cyclists SET name="STEWART Campbell" WHERE cyclistId=712;
UPDATE cyclists SET name="BEADLE Hamish" WHERE cyclistId=713;
UPDATE cyclists SET name="BRAND Sam" WHERE cyclistId=714;
UPDATE cyclists SET name="CLANCY Stephen" WHERE cyclistId=715;
UPDATE cyclists SET name="DAUGE Lucas" WHERE cyclistId=716;
UPDATE cyclists SET name="DE GRAEVE Quinten" WHERE cyclistId=717;
UPDATE cyclists SET name="DE KEIJZER Gerd" WHERE cyclistId=718;
UPDATE cyclists SET name="DUNNEWIND Jan" WHERE cyclistId=719;
UPDATE cyclists SET name="IRVINE Declan" WHERE cyclistId=720;
UPDATE cyclists SET name="KOPECKÝ Matyáš" WHERE cyclistId=721;
UPDATE cyclists SET name="KUSZTOR Péter" WHERE cyclistId=722;
UPDATE cyclists SET name="LOZANO David" WHERE cyclistId=723;
UPDATE cyclists SET name="PERCRULE Doriand" WHERE cyclistId=724;
UPDATE cyclists SET name="PERON Andrea" WHERE cyclistId=725;
UPDATE cyclists SET name="PERRACCHIONE Alessandro" WHERE cyclistId=726;
UPDATE cyclists SET name="PHIPPEN Logan" WHERE cyclistId=727;
UPDATE cyclists SET name="PLANET Charles" WHERE cyclistId=728;
UPDATE cyclists SET name="POLGA Antonio" WHERE cyclistId=729;
UPDATE cyclists SET name="POLI Umberto" WHERE cyclistId=730;
UPDATE cyclists SET name="RIDOLFO Filippo" WHERE cyclistId=731;
UPDATE cyclists SET name="SMITH Nathan" WHERE cyclistId=732;
UPDATE cyclists SET name="BAIS Davide" WHERE cyclistId=733;
UPDATE cyclists SET name="MAESTRI Mirco" WHERE cyclistId=734;
UPDATE cyclists SET name="PIGANZOLI Davide" WHERE cyclistId=735;
UPDATE cyclists SET name="BAIS Mattia" WHERE cyclistId=736;
UPDATE cyclists SET name="DE CASSAN Davide" WHERE cyclistId=737;
UPDATE cyclists SET name="DOUBLE Paul" WHERE cyclistId=738;
UPDATE cyclists SET name="FABBRO Matteo" WHERE cyclistId=739;
UPDATE cyclists SET name="FETTER Erik" WHERE cyclistId=740;
UPDATE cyclists SET name="GAROSIO Andrea" WHERE cyclistId=741;
UPDATE cyclists SET name="GOMEZ German Dario" WHERE cyclistId=742;
UPDATE cyclists SET name="LONARDI Giovanni" WHERE cyclistId=743;
UPDATE cyclists SET name="MARTIN Alex" WHERE cyclistId=744;
UPDATE cyclists SET name="MARTIN David" WHERE cyclistId=745;
UPDATE cyclists SET name="MUNOZ Francisco" WHERE cyclistId=746;
UPDATE cyclists SET name="PENALVER Manuel" WHERE cyclistId=747;
UPDATE cyclists SET name="PIETROBON Andrea" WHERE cyclistId=748;
UPDATE cyclists SET name="RESTREPO Jhonatan" WHERE cyclistId=749;
UPDATE cyclists SET name="SERRANO Javier" WHERE cyclistId=750;
UPDATE cyclists SET name="SEVILLA Diego Pablo" WHERE cyclistId=751;
UPDATE cyclists SET name="TERCERO Fer0do" WHERE cyclistId=752;
UPDATE cyclists SET name="BURGAUDEAU Mathieu" WHERE cyclistId=753;
UPDATE cyclists SET name="VAN GESTEL Dries" WHERE cyclistId=754;
UPDATE cyclists SET name="DUJARDIN Sandy" WHERE cyclistId=755;
UPDATE cyclists SET name="LATOUR Pierre" WHERE cyclistId=756;
UPDATE cyclists SET name="FERRON Valentin" WHERE cyclistId=757;
UPDATE cyclists SET name="TURGIS Anthony" WHERE cyclistId=758;
UPDATE cyclists SET name="CRAS Steff" WHERE cyclistId=759;
UPDATE cyclists SET name="SOUPE Geoffrey" WHERE cyclistId=760;
UPDATE cyclists SET name="TESSON Jason" WHERE cyclistId=761;
UPDATE cyclists SET name="BONIFACE Lucas" WHERE cyclistId=762;
UPDATE cyclists SET name="BONNET Thomas" WHERE cyclistId=763;
UPDATE cyclists SET name="DOUBEY Fabien" WHERE cyclistId=764;
UPDATE cyclists SET name="GACHIGNARD Thomas" WHERE cyclistId=765;
UPDATE cyclists SET name="GRELLIER Fabien" WHERE cyclistId=766;
UPDATE cyclists SET name="JEANNIERE Emilien" WHERE cyclistId=767;
UPDATE cyclists SET name="JEGAT Jordan" WHERE cyclistId=768;
UPDATE cyclists SET name="JOUSSEAUME Alan" WHERE cyclistId=769;
UPDATE cyclists SET name="MANZIN Lorrenzo" WHERE cyclistId=770;
UPDATE cyclists SET name="OURSELIN Paul" WHERE cyclistId=771;
UPDATE cyclists SET name="SIMON Julien" WHERE cyclistId=772;
UPDATE cyclists SET name="VADIC Baptiste" WHERE cyclistId=773;
UPDATE cyclists SET name="VERCHER Matteo" WHERE cyclistId=774;
UPDATE cyclists SET name="VUILLERMOZ Alexis" WHERE cyclistId=775;
UPDATE cyclists SET name="TRENTIN Matteo" WHERE cyclistId=776;
UPDATE cyclists SET name="DAINESE Alberto" WHERE cyclistId=777;
UPDATE cyclists SET name="KAMP Alexander" WHERE cyclistId=778;
UPDATE cyclists SET name="DE KLEINJ Arvid" WHERE cyclistId=779;
UPDATE cyclists SET name="MAYROHFER Marius" WHERE cyclistId=780;
UPDATE cyclists SET name="STORER Michael" WHERE cyclistId=781;
UPDATE cyclists SET name="BOHLI Tom" WHERE cyclistId=782;
UPDATE cyclists SET name="BRENNER Marco" WHERE cyclistId=783;
UPDATE cyclists SET name="BRUN Nils" WHERE cyclistId=784;
UPDATE cyclists SET name="CHARRIN Aloïs" WHERE cyclistId=785;
UPDATE cyclists SET name="ERIKSSON Jacob" WHERE cyclistId=786;
UPDATE cyclists SET name="ERIKSSON Lucas" WHERE cyclistId=787;
UPDATE cyclists SET name="FROIDEVAUX Robin" WHERE cyclistId=788;
UPDATE cyclists SET name="HEMING Mika" WHERE cyclistId=789;
UPDATE cyclists SET name="KELEMEN Petr" WHERE cyclistId=790;
UPDATE cyclists SET name="KLUCKERS Arthur" WHERE cyclistId=791;
UPDATE cyclists SET name="KOLZE XHANGIZI Sebastian" WHERE cyclistId=792;
UPDATE cyclists SET name="KRIEGER Alexander" WHERE cyclistId=793;
UPDATE cyclists SET name="PELLAUD Simon" WHERE cyclistId=794;
UPDATE cyclists SET name="PLUIMERS Rick" WHERE cyclistId=795;
UPDATE cyclists SET name="REICHENBACH Sebastien" WHERE cyclistId=796;
UPDATE cyclists SET name="STORK Florian" WHERE cyclistId=797;
UPDATE cyclists SET name="SUTER Joel" WHERE cyclistId=798;
UPDATE cyclists SET name="THALMANN Roland" WHERE cyclistId=799;
UPDATE cyclists SET name="VOISARD Yannis" WHERE cyclistId=800;
UPDATE cyclists SET name="WILKSCH Hannes" WHERE cyclistId=801;
UPDATE cyclists SET name="WIRTGEN Luc" WHERE cyclistId=802;
UPDATE cyclists SET name="ZIJLGAARD Maikel" WHERE cyclistId=803;
UPDATE cyclists SET name="POGAČAR Tadej" WHERE cyclistId=804;
UPDATE cyclists SET name="YATES Adam" WHERE cyclistId=805;
UPDATE cyclists SET name="ALMEIDA João" WHERE cyclistId=806;
UPDATE cyclists SET name="HIRSCHI Marc" WHERE cyclistId=807;
UPDATE cyclists SET name="AYUSO Juan" WHERE cyclistId=808;
UPDATE cyclists SET name="MCNULTY Brandon" WHERE cyclistId=809;
UPDATE cyclists SET name="SIVAKOV Pavel" WHERE cyclistId=810;
UPDATE cyclists SET name="VINE Jay" WHERE cyclistId=811;
UPDATE cyclists SET name="MOLANO Juan Sebastián" WHERE cyclistId=812;
UPDATE cyclists SET name="ULISSI Diego" WHERE cyclistId=813;
UPDATE cyclists SET name="GROßSCHARTNER Felix" WHERE cyclistId=814;
UPDATE cyclists SET name="WELLENS Tim" WHERE cyclistId=815;
UPDATE cyclists SET name="BJERG Mikkel" WHERE cyclistId=816;
UPDATE cyclists SET name="SOLER Marc" WHERE cyclistId=817;
UPDATE cyclists SET name="POLITT Nils" WHERE cyclistId=818;
UPDATE cyclists SET name="MAJKA Rafał" WHERE cyclistId=819;
UPDATE cyclists SET name="BAX Sjoerd" WHERE cyclistId=820;
UPDATE cyclists SET name="FISHER-BLACK Finn" WHERE cyclistId=821;
UPDATE cyclists SET name="MORGADO António" WHERE cyclistId=822;
UPDATE cyclists SET name="ARRIETA Igor" WHERE cyclistId=823;
UPDATE cyclists SET name="BARONCINI Filippo" WHERE cyclistId=824;
UPDATE cyclists SET name="CHRISTEN Jan" WHERE cyclistId=825;
UPDATE cyclists SET name="COVI Alessandro" WHERE cyclistId=826;
UPDATE cyclists SET name="DEL TORO Isaac" WHERE cyclistId=827;
UPDATE cyclists SET name="HODEG Alvaro" WHERE cyclistId=828;
UPDATE cyclists SET name="LAENGEN Vegard Stake" WHERE cyclistId=829;
UPDATE cyclists SET name="NOVAK Domen" WHERE cyclistId=830;
UPDATE cyclists SET name="OLIVEIRA Ivo" WHERE cyclistId=831;
UPDATE cyclists SET name="OLIVEIRA Rui" WHERE cyclistId=832;
UPDATE cyclists SET name="VINK Michael" WHERE cyclistId=833;
UPDATE cyclists SET name="JOHANNESSEN Tobias Halland" WHERE cyclistId=834;
UPDATE cyclists SET name="KRISTOFF Alexander" WHERE cyclistId=835;
UPDATE cyclists SET name="TILLER Rasmus" WHERE cyclistId=836;
UPDATE cyclists SET name="WAERENSKJOLD Soren" WHERE cyclistId=837;
UPDATE cyclists SET name="CORT NIELSEN Magnus" WHERE cyclistId=838;
UPDATE cyclists SET name="LEKNESSUND Andreas" WHERE cyclistId=839;
UPDATE cyclists SET name="DVERSNES Fredrik" WHERE cyclistId=840;
UPDATE cyclists SET name="ABRAHAMSEN Jonas" WHERE cyclistId=841;
UPDATE cyclists SET name="ANDERSEN Idar" WHERE cyclistId=842;
UPDATE cyclists SET name="BENDIXEN Louis" WHERE cyclistId=843;
UPDATE cyclists SET name="BEVORT Carl-Frederik" WHERE cyclistId=844;
UPDATE cyclists SET name="BLIKRA Erlend" WHERE cyclistId=845;
UPDATE cyclists SET name="BLUME LEVY William" WHERE cyclistId=846;
UPDATE cyclists SET name="FREDHEIM Stian" WHERE cyclistId=847;
UPDATE cyclists SET name="GUDMESTAD Tord" WHERE cyclistId=848;
UPDATE cyclists SET name="HOELGAARD Markus" WHERE cyclistId=849;
UPDATE cyclists SET name="HOLTER Adne" WHERE cyclistId=850;
UPDATE cyclists SET name="HVIDEBERG Jonas Iversby" WHERE cyclistId=851;
UPDATE cyclists SET name="JOHANNESSEN Anders Halland" WHERE cyclistId=852;
UPDATE cyclists SET name="KULSET Sindre" WHERE cyclistId=853;
UPDATE cyclists SET name="KULSET Johannes" WHERE cyclistId=854;
UPDATE cyclists SET name="KULSET Magnus" WHERE cyclistId=855;
UPDATE cyclists SET name="LARSEN Niklas" WHERE cyclistId=856;
UPDATE cyclists SET name="LOLAND Sakarias Koller" WHERE cyclistId=857;
UPDATE cyclists SET name="RESELL Erik Nordsaeter" WHERE cyclistId=858;
UPDATE cyclists SET name="SANDER HANSEN Marcus" WHERE cyclistId=859;
UPDATE cyclists SET name="SKAARSETH Anders" WHERE cyclistId=860;
UPDATE cyclists SET name="URIANSTAD Martin" WHERE cyclistId=861;
UPDATE cyclists SET name="WALLIN Rasmus Bogh" WHERE cyclistId=862;
UPDATE cyclists SET name="FIORELLI Filippo" WHERE cyclistId=863;
UPDATE cyclists SET name="PELLIZZARI Giulio" WHERE cyclistId=864;
UPDATE cyclists SET name="TONELLI Alessandro" WHERE cyclistId=865;
UPDATE cyclists SET name="BIAGINI Federico" WHERE cyclistId=866;
UPDATE cyclists SET name="COLNAGHI Luca" WHERE cyclistId=867;
UPDATE cyclists SET name="CONFORTI Lorenzo" WHERE cyclistId=868;
UPDATE cyclists SET name="COVILI Luca" WHERE cyclistId=869;
UPDATE cyclists SET name="GABBURO Davide" WHERE cyclistId=870;
UPDATE cyclists SET name="LUCCA Riccardo" WHERE cyclistId=871;
UPDATE cyclists SET name="MAGLI Filippo" WHERE cyclistId=872;
UPDATE cyclists SET name="MARCELLUSI Martin" WHERE cyclistId=873;
UPDATE cyclists SET name="MARTINELLI Alessio" WHERE cyclistId=874;
UPDATE cyclists SET name="PALETTI Luca" WHERE cyclistId=875;
UPDATE cyclists SET name="PINARELLO Alessandro" WHERE cyclistId=876;
UPDATE cyclists SET name="PINAZZI Mattia" WHERE cyclistId=877;
UPDATE cyclists SET name="ROJAS Vicente" WHERE cyclistId=878;
UPDATE cyclists SET name="SCALCO Matteo" WHERE cyclistId=879;
UPDATE cyclists SET name="TAROZZI Manuele" WHERE cyclistId=880;
UPDATE cyclists SET name="TOLIO Alex" WHERE cyclistId=881;
UPDATE cyclists SET name="TURCONI Filippo" WHERE cyclistId=882;
UPDATE cyclists SET name="ZANONCELLO Enrico" WHERE cyclistId=883;
UPDATE cyclists SET name="ZOCCARATO Samuele" WHERE cyclistId=884;
UPDATE cyclists SET name="VINGEGAARD Jonas" WHERE cyclistId=885;
UPDATE cyclists SET name="VAN AERT Wout" WHERE cyclistId=886;
UPDATE cyclists SET name="KUSS Sepp" WHERE cyclistId=887;
UPDATE cyclists SET name="LAPORTE Christophe" WHERE cyclistId=888;
UPDATE cyclists SET name="KOOIJ Olav" WHERE cyclistId=889;
UPDATE cyclists SET name="BENOOT Tiesj" WHERE cyclistId=890;
UPDATE cyclists SET name="JORGENSON Matteo" WHERE cyclistId=891;
UPDATE cyclists SET name="UIJTDEBROECKS Cian" WHERE cyclistId=892;
UPDATE cyclists SET name="VALTER Attila" WHERE cyclistId=893;
UPDATE cyclists SET name="KELDERMAN Wilco" WHERE cyclistId=894;
UPDATE cyclists SET name="VAN BAARLE Dylan" WHERE cyclistId=895;
UPDATE cyclists SET name="TULETT Ben" WHERE cyclistId=896;
UPDATE cyclists SET name="VADER Milan" WHERE cyclistId=897;
UPDATE cyclists SET name="VAN DIJKE Tim" WHERE cyclistId=898;
UPDATE cyclists SET name="HAGENES Per Strand" WHERE cyclistId=899;
UPDATE cyclists SET name="LEMMEN Bert" WHERE cyclistId=900;
UPDATE cyclists SET name="AFFINI Edoardo" WHERE cyclistId=901;
UPDATE cyclists SET name="BOUWMAN Koen" WHERE cyclistId=902;
UPDATE cyclists SET name="GESINK Robert" WHERE cyclistId=903;
UPDATE cyclists SET name="GLOAG Thomas" WHERE cyclistId=904;
UPDATE cyclists SET name="HOFSTEDE Lennard" WHERE cyclistId=905;
UPDATE cyclists SET name="KRUIJSWIJK Steven" WHERE cyclistId=906;
UPDATE cyclists SET name="STAUNE-MITTET Johannes" WHERE cyclistId=907;
UPDATE cyclists SET name="TRATNIK Jan" WHERE cyclistId=908;
UPDATE cyclists SET name="VAN BELLE Loe" WHERE cyclistId=909;
UPDATE cyclists SET name="VAN DER SANDE Tosh" WHERE cyclistId=910;
UPDATE cyclists SET name="VAN DIJKE Mick" WHERE cyclistId=911;
UPDATE cyclists SET name="BOVEN Lars" WHERE cyclistId=912;
UPDATE cyclists SET name="PLOWRIGHT Jensen" WHERE cyclistId=913;
UPDATE cyclists SET name="UHLIG Henri" WHERE cyclistId=914;
UPDATE cyclists SET name="LE BERRE Mathis" WHERE cyclistId=915;
UPDATE cyclists SET name="CHZHAN Igor" WHERE cyclistId=916;
UPDATE cyclists SET name="GAROFOLI Gianmarco" WHERE cyclistId=917;
UPDATE cyclists SET name="SYRITSA Gleb" WHERE cyclistId=918;
UPDATE cyclists SET name="VINOKUROV Nicolas" WHERE cyclistId=919;
UPDATE cyclists SET name="LOPEZ Harold Martin" WHERE cyclistId=920;
UPDATE cyclists SET name="BRUTTOMESSO Alberto" WHERE cyclistId=921;
UPDATE cyclists SET name="KEPPLINGER Rainer" WHERE cyclistId=922;
UPDATE cyclists SET name="MIHOLJEVIĆ Fran" WHERE cyclistId=923;
UPDATE cyclists SET name="PICKERING Finlay" WHERE cyclistId=924;
UPDATE cyclists SET name="SCOTT Cameron" WHERE cyclistId=925;
UPDATE cyclists SET name="TU Sergio" WHERE cyclistId=926;
UPDATE cyclists SET name="DE MEESTER Luca" WHERE cyclistId=927;
UPDATE cyclists SET name="PORTSMOUTH Tom" WHERE cyclistId=928;
UPDATE cyclists SET name="SALBY Alexander" WHERE cyclistId=929;
UPDATE cyclists SET name="VAN BOVEN Luca" WHERE cyclistId=930;
UPDATE cyclists SET name="VAN DER BEKEN Aaron" WHERE cyclistId=931;
UPDATE cyclists SET name="VANDEPITTE Nathan" WHERE cyclistId=932;
UPDATE cyclists SET name="HAJEK Alexander" WHERE cyclistId=933;
UPDATE cyclists SET name="HERZOG Emil" WHERE cyclistId=934;
UPDATE cyclists SET name="LIPOWITZ Florian" WHERE cyclistId=935;
UPDATE cyclists SET name="ALLENO Clément" WHERE cyclistId=936;
UPDATE cyclists SET name="ALVAREZ Rodrigo" WHERE cyclistId=937;
UPDATE cyclists SET name="FAGUNDEZ Eric Antonio" WHERE cyclistId=938;
UPDATE cyclists SET name="FRANCO Alejandro" WHERE cyclistId=939;
UPDATE cyclists SET name="JACKSON George" WHERE cyclistId=940;
UPDATE cyclists SET name="CHUMIL Sergio Geovani" WHERE cyclistId=941;
UPDATE cyclists SET name="ARRIOLA-BENGOA Julen" WHERE cyclistId=942;
UPDATE cyclists SET name="BABOR Daniel" WHERE cyclistId=943;
UPDATE cyclists SET name="BALDERSTONE Abel" WHERE cyclistId=944;
UPDATE cyclists SET name="BARTA Tomas" WHERE cyclistId=945;
UPDATE cyclists SET name="FERNANDEZ Samuel" WHERE cyclistId=946;
UPDATE cyclists SET name="LOPEZ Joseba" WHERE cyclistId=947;
UPDATE cyclists SET name="DEBEAUMARCHE Nicolas" WHERE cyclistId=948;
UPDATE cyclists SET name="MAHOUDO Nolann" WHERE cyclistId=949;
UPDATE cyclists SET name="MARIAULT Axel" WHERE cyclistId=950;
UPDATE cyclists SET name="WOOD Harrison" WHERE cyclistId=951;
UPDATE cyclists SET name="GAUTHERAT Pierre" WHERE cyclistId=952;
UPDATE cyclists SET name="POLLEFLIET Gianluca" WHERE cyclistId=953;
UPDATE cyclists SET name="TRONCHON Bastien" WHERE cyclistId=954;
UPDATE cyclists SET name="BELOKI Markel" WHERE cyclistId=955;
UPDATE cyclists SET name="NERURKAR Lukas" WHERE cyclistId=956;
UPDATE cyclists SET name="RAFFERTY Darren" WHERE cyclistId=957;
UPDATE cyclists SET name="ROOTKIN-GRAY Jack" WHERE cyclistId=958;
UPDATE cyclists SET name="TODOME Yuhi" WHERE cyclistId=959;
UPDATE cyclists SET name="AZNAR Unai" WHERE cyclistId=960;
UPDATE cyclists SET name="CASTRILLO Pablo" WHERE cyclistId=961;
UPDATE cyclists SET name="GUTIERREZ Jorge" WHERE cyclistId=962;
UPDATE cyclists SET name="RETEGI Mikel" WHERE cyclistId=963;
UPDATE cyclists SET name="URIARTE Diego" WHERE cyclistId=964;
UPDATE cyclists SET name="ALUSTIZA Nicolas" WHERE cyclistId=965;
UPDATE cyclists SET name="BERASATEGI Xabier" WHERE cyclistId=966;
UPDATE cyclists SET name="LOPEZ DE ABETXUKO Andoni" WHERE cyclistId=967;
UPDATE cyclists SET name="MINTEGUI Iker" WHERE cyclistId=968;
UPDATE cyclists SET name="ZUBELDIA Unai" WHERE cyclistId=969;
UPDATE cyclists SET name="GERMANI Lorenzo" WHERE cyclistId=970;
UPDATE cyclists SET name="LE HUITOUZE Eddy" WHERE cyclistId=971;
UPDATE cyclists SET name="PALENI Enzo" WHERE cyclistId=972;
UPDATE cyclists SET name="THOMPSON Reuben" WHERE cyclistId=973;
UPDATE cyclists SET name="AUGUST Andrew" WHERE cyclistId=974;
UPDATE cyclists SET name="STORM Theodor" WHERE cyclistId=975;
UPDATE cyclists SET name="HAYTER Leo" WHERE cyclistId=976;
UPDATE cyclists SET name="LEONARD Michael" WHERE cyclistId=977;
UPDATE cyclists SET name="FAURE PROST Alexy" WHERE cyclistId=978;
UPDATE cyclists SET name="VAN SINTMAARTENSDIJK Roel" WHERE cyclistId=979;
UPDATE cyclists SET name="FRIGO Marco" WHERE cyclistId=980;
UPDATE cyclists SET name="HOLLYMAN Mason" WHERE cyclistId=981;
UPDATE cyclists SET name="KOGUT Oded" WHERE cyclistId=982;
UPDATE cyclists SET name="PICKRELL Riley" WHERE cyclistId=983;
UPDATE cyclists SET name="RAISBERG Nadav" WHERE cyclistId=984;
UPDATE cyclists SET name="ADAMIETZ Johannes" WHERE cyclistId=985;
UPDATE cyclists SET name="SLOCK Liam" WHERE cyclistId=986;
UPDATE cyclists SET name="ROMEO Ivan" WHERE cyclistId=987;
UPDATE cyclists SET name="PIETROBON Andrea" WHERE cyclistId=988;
UPDATE cyclists SET name="SERRANO Javier" WHERE cyclistId=989;
UPDATE cyclists SET name="TERCERO Fernando" WHERE cyclistId=990;
UPDATE cyclists SET name="ABREHA Negasi Haylu" WHERE cyclistId=991;
UPDATE cyclists SET name="CALZONI Walter" WHERE cyclistId=992;
UPDATE cyclists SET name="CAMPRUBI Marcel" WHERE cyclistId=993;
UPDATE cyclists SET name="CHRISTEN Fabio" WHERE cyclistId=994;
UPDATE cyclists SET name="COLOMBO Filippo" WHERE cyclistId=995;
UPDATE cyclists SET name="PARISINI Nicolo" WHERE cyclistId=996;
UPDATE cyclists SET name="BASTIAENS Ayco" WHERE cyclistId=997;
UPDATE cyclists SET name="GELDERS Gil" WHERE cyclistId=998;
UPDATE cyclists SET name="HUBY Antoine" WHERE cyclistId=999;
UPDATE cyclists SET name="MAGNIER Paul" WHERE cyclistId=1000;
UPDATE cyclists SET name="VANGHELUWE Warre" WHERE cyclistId=1001;
UPDATE cyclists SET name="BOMBOI Davide" WHERE cyclistId=1002;
UPDATE cyclists SET name="CHRISTOPHERSEN Cedrik Bakke" WHERE cyclistId=1003;
UPDATE cyclists SET name="GELEIJN Owen" WHERE cyclistId=1004;
UPDATE cyclists SET name="HUENS Axel" WHERE cyclistId=1005;
UPDATE cyclists SET name="HUYET Baptiste" WHERE cyclistId=1006;
UPDATE cyclists SET name="KOPECKÝ Tomáš" WHERE cyclistId=1007;
UPDATE cyclists SET name="BLOEM Joren" WHERE cyclistId=1008;
UPDATE cyclists SET name="AMELLA MATTEO" WHERE cyclistId=1009;
UPDATE cyclists SET name="BALDACCINI Davide" WHERE cyclistId=1010;
UPDATE cyclists SET name="MASOTTO Giulio" WHERE cyclistId=1011;
UPDATE cyclists SET name="OLIVERO Simone" WHERE cyclistId=1012;
UPDATE cyclists SET name="ZAMBELLI Samuele" WHERE cyclistId=1013;
UPDATE cyclists SET name="VAN Uden Casper" WHERE cyclistId=1014;
UPDATE cyclists SET name="EDDY Patrick" WHERE cyclistId=1015;
UPDATE cyclists SET name="FLYNN Sean" WHERE cyclistId=1016;
UPDATE cyclists SET name="LEIJNSE Enzo" WHERE cyclistId=1017;
UPDATE cyclists SET name="VAN DEN BROEK Frank" WHERE cyclistId=1018;
UPDATE cyclists SET name="CLAEYS Arno" WHERE cyclistId=1019;
UPDATE cyclists SET name="CLYNHENS Toon" WHERE cyclistId=1020;
UPDATE cyclists SET name="CRAPS Lars" WHERE cyclistId=1021;
UPDATE cyclists SET name="DEJAEGHER Jasper" WHERE cyclistId=1022;
UPDATE cyclists SET name="DEWEIRDT Siebe" WHERE cyclistId=1023;
UPDATE cyclists SET name="GERITS Vince" WHERE cyclistId=1024;
UPDATE cyclists SET name="VAN HEMELEN Vincent" WHERE cyclistId=1025;
UPDATE cyclists SET name="VANDENBRANDEN Noah" WHERE cyclistId=1026;
UPDATE cyclists SET name="VANDENSTORME Dylan" WHERE cyclistId=1027;
UPDATE cyclists SET name="BERHE Welay Hagos" WHERE cyclistId=1028;
UPDATE cyclists SET name="DE PRETTO Davide" WHERE cyclistId=1029;
UPDATE cyclists SET name="FOLDAGER Anders" WHERE cyclistId=1030;
UPDATE cyclists SET name="PORTER Rudy" WHERE cyclistId=1031;
UPDATE cyclists SET name="QUICK Blake" WHERE cyclistId=1032;
UPDATE cyclists SET name="BONNET Thomas" WHERE cyclistId=1033;
UPDATE cyclists SET name="GACHIGNARD Thomas" WHERE cyclistId=1034;
UPDATE cyclists SET name="JEGAT Jordan" WHERE cyclistId=1035;
UPDATE cyclists SET name="VADIC Baptiste" WHERE cyclistId=1036;
UPDATE cyclists SET name="JEANNIERE Emilien" WHERE cyclistId=1037;
UPDATE cyclists SET name="VERCHER Matteo" WHERE cyclistId=1038;
UPDATE cyclists SET name="ERIKSSON Jacob" WHERE cyclistId=1039;
UPDATE cyclists SET name="MORGADO António" WHERE cyclistId=1040;
UPDATE cyclists SET name="BENDIXEN Louis" WHERE cyclistId=1041;
UPDATE cyclists SET name="BEVORT Carl-Frederik" WHERE cyclistId=1042;
UPDATE cyclists SET name="FREDHEIM Stian" WHERE cyclistId=1043;
UPDATE cyclists SET name="KULSET Johannes" WHERE cyclistId=1044;
UPDATE cyclists SET name="KULSET Magnus" WHERE cyclistId=1045;
UPDATE cyclists SET name="SANDER HANSEN Marcus" WHERE cyclistId=1046;
UPDATE cyclists SET name="LOLAND Sakarias Koller" WHERE cyclistId=1047;
UPDATE cyclists SET name="BIAGINI Federico" WHERE cyclistId=1048;
UPDATE cyclists SET name="CONFORTI Lorenzo" WHERE cyclistId=1049;
UPDATE cyclists SET name="LUCCA Riccardo" WHERE cyclistId=1050;
UPDATE cyclists SET name="PALETTI Luca" WHERE cyclistId=1051;
UPDATE cyclists SET name="PINAZZI Mattia" WHERE cyclistId=1052;
UPDATE cyclists SET name="SCALCO Matteo" WHERE cyclistId=1053;
UPDATE cyclists SET name="TURCONI Filippo" WHERE cyclistId=1054;
UPDATE cyclists SET name="VAN BELLE Loe" WHERE cyclistId=1055;
UPDATE cyclists SET name="MIHKELS Madis" WHERE cyclistId=1056;
UPDATE cyclists SET name="PIGANZOLI Davide" WHERE cyclistId=1057;
UPDATE cyclists SET name="COSTIOU Ewen" WHERE cyclistId=1058;
UPDATE cyclists SET name="RYAN Archie" WHERE cyclistId=1059;
UPDATE cyclists SET name="WATSON Samuel" WHERE cyclistId=1060;
UPDATE cyclists SET name="BUSATTO Francesco" WHERE cyclistId=1061;
UPDATE cyclists SET name="RICCITELLO Matthew" WHERE cyclistId=1062;
UPDATE cyclists SET name="LAMPERTI Luke" WHERE cyclistId=1063;
UPDATE cyclists SET name="LECERF William Junior" WHERE cyclistId=1064;
UPDATE cyclists SET name="ANDRESEN Tobias Lund" WHERE cyclistId=1065;
UPDATE cyclists SET name="DEL TORO Isaac" WHERE cyclistId=1066;
UPDATE cyclists SET name="HAGENES Per Strand" WHERE cyclistId=1067;
UPDATE cyclists SET name="GLOAG Thomas" WHERE cyclistId=1068;
UPDATE cyclists SET name="STAUNE-MITTET Johannes" WHERE cyclistId=1069;
UPDATE cyclists SET name="TESSON JASON" WHERE cyclistId=1070;
UPDATE cyclists SET name="SHEEHAN Riley" WHERE cyclistId=1071;
UPDATE cyclists SET name="NYS Thibau" WHERE cyclistId=1072;
UPDATE cyclists SET name="ONLEY Oscar" WHERE cyclistId=1073;
UPDATE cyclists SET name="DINHAM Matthew" WHERE cyclistId=1074;
UPDATE cyclists SET name="KIELICH Timo" WHERE cyclistId=1075;
UPDATE cyclists SET name="PITHIE Laurence" WHERE cyclistId=1076;
UPDATE cyclists SET name="ENGELHARDT Felix" WHERE cyclistId=1077;
UPDATE cyclists SET name="TARLING Joshua" WHERE cyclistId=1078;
UPDATE cyclists SET name="POOLE Max" WHERE cyclistId=1079;
UPDATE cyclists SET name="VAN EETVELT Lennert" WHERE cyclistId=1080;
UPDATE cyclists SET name="MARTINEZ Lenny" WHERE cyclistId=1081;
UPDATE cyclists SET name="GREGOIRE Romain" WHERE cyclistId=1082;
UPDATE cyclists SET name="GEE Derek" WHERE cyclistId=1083;
UPDATE cyclists SET name="VERGALLITO Luca" WHERE cyclistId=1084;
UPDATE cyclists SET name="KUZMIN Anton" WHERE cyclistId=1085;
UPDATE cyclists SET name="MARUKHIN Daniil" WHERE cyclistId=1086;
UPDATE cyclists SET name="BURATTI Nicolo" WHERE cyclistId=1087;
UPDATE cyclists SET name="VILLA Giacomo" WHERE cyclistId=1088;
UPDATE cyclists SET name="PERSICO Davide" WHERE cyclistId=1089;
UPDATE cyclists SET name="VERMOOTE Jelle" WHERE cyclistId=1090;
UPDATE cyclists SET name="MATTHYS Louka" WHERE cyclistId=1091;
UPDATE cyclists SET name="TEUGELS Lennert" WHERE cyclistId=1092;
UPDATE cyclists SET name="SAINBAYAR Jambaljamts" WHERE cyclistId=1093;
UPDATE cyclists SET name="BOUGLAS Georgios" WHERE cyclistId=1094;
UPDATE cyclists SET name="FERNANDEZ Sinuhé" WHERE cyclistId=1095;
UPDATE cyclists SET name="FERNANDEZ Miguel Angel" WHERE cyclistId=1096;
UPDATE cyclists SET name="DELGADO David" WHERE cyclistId=1097;
UPDATE cyclists SET name="HAILEMICHAEL Mulu Kinfe" WHERE cyclistId=1098;
UPDATE cyclists SET name="SORARRAIN Gorka" WHERE cyclistId=1099;
UPDATE cyclists SET name="GUARDENO Jaume" WHERE cyclistId=1100;
UPDATE cyclists SET name="SILVA Guillermo Thomas" WHERE cyclistId=1101;
UPDATE cyclists SET name="KNIGHT Oliver" WHERE cyclistId=1102;
UPDATE cyclists SET name="LABROSSE Jordan" WHERE cyclistId=1103;
UPDATE cyclists SET name="VAN DER LEE Jardi Christiaan" WHERE cyclistId=1104;
UPDATE cyclists SET name="AZNAR Hugio" WHERE cyclistId=1105;
UPDATE cyclists SET name="AZPARREN Enekoitz" WHERE cyclistId=1106;
UPDATE cyclists SET name="DE POOTER Dries" WHERE cyclistId=1107;
UPDATE cyclists SET name="SEGAERT Alec" WHERE cyclistId=1108;
UPDATE cyclists SET name="VAN DE PAAR Jarne" WHERE cyclistId=1109;
UPDATE cyclists SET name="MORO Manlio" WHERE cyclistId=1110;
UPDATE cyclists SET name="MILESI Lorenzo" WHERE cyclistId=1111;
UPDATE cyclists SET name="DE CASSAN Davide" WHERE cyclistId=1112;
UPDATE cyclists SET name="GOMEZ German Dario" WHERE cyclistId=1113;
UPDATE cyclists SET name="MUNOZ Francisco" WHERE cyclistId=1114;
UPDATE cyclists SET name="MONK Cyrus" WHERE cyclistId=1115;
UPDATE cyclists SET name="KYFFIN Zeb" WHERE cyclistId=1116;
UPDATE cyclists SET name="NIELSEN Sebastian" WHERE cyclistId=1117;
UPDATE cyclists SET name="PAIGE Charles" WHERE cyclistId=1118;
UPDATE cyclists SET name="JOHANNINK Jelle" WHERE cyclistId=1119;
UPDATE cyclists SET name="MAIRE Adrien" WHERE cyclistId=1120;
UPDATE cyclists SET name="DE VRIES Hartthijs" WHERE cyclistId=1121;
UPDATE cyclists SET name="BOUTS Jordy" WHERE cyclistId=1122;
UPDATE cyclists SET name="LOOCKX Lander" WHERE cyclistId=1123;
UPDATE cyclists SET name="STOCKMAN Abram" WHERE cyclistId=1124;
UPDATE cyclists SET name="TOUPALIK Adam" WHERE cyclistId=1125;
UPDATE cyclists SET name="QUARTUCCI Lorenzo" WHERE cyclistId=1126;
UPDATE cyclists SET name="DEBONS Antoine" WHERE cyclistId=1127;
UPDATE cyclists SET name="TSARENKO Kyrylo" WHERE cyclistId=1128;
UPDATE cyclists SET name="DARBELLAY Valentin" WHERE cyclistId=1129;
UPDATE cyclists SET name="STÖCKLI Jan" WHERE cyclistId=1130;
UPDATE cyclists SET name="MARIS Elias" WHERE cyclistId=1131;
UPDATE cyclists SET name="VANDEVELDE Yentl" WHERE cyclistId=1132;
UPDATE cyclists SET name="VERCOUILLIE Victor" WHERE cyclistId=1133;
UPDATE cyclists SET name="PARRACCHIONE Alessandro" WHERE cyclistId=1134;
UPDATE cyclists SET name="DE GRAEVE Quinten" WHERE cyclistId=1135;
UPDATE cyclists SET name="PERCRULE Doriand" WHERE cyclistId=1136;
UPDATE cyclists SET name="POLGA Antonio" WHERE cyclistId=1137;
UPDATE cyclists SET name="SMITH Nathan" WHERE cyclistId=1138;
UPDATE cyclists SET name="BONIFACE Lucas" WHERE cyclistId=1139;
UPDATE cyclists SET name="HEMING Mika" WHERE cyclistId=1140;
UPDATE cyclists SET name="WILKSCH Hannes" WHERE cyclistId=1141;
UPDATE cyclists SET name="KOLZE CHABGIZI Sebastian" WHERE cyclistId=1142;
UPDATE cyclists SET name="KLUCKERS Arthur" WHERE cyclistId=1143;
UPDATE cyclists SET name="PLUIMERS Rick" WHERE cyclistId=1144;
UPDATE cyclists SET name="CHRISTEN Jan" WHERE cyclistId=1145;
UPDATE cyclists SET name="MAGLI Filippo" WHERE cyclistId=1146;
UPDATE cyclists SET name="ROJAS Vicente" WHERE cyclistId=1147;
UPDATE cyclists SET name="LEMMEN Bart" WHERE cyclistId=1148;
