UPDATE races SET name="Tour Down Under" WHERE raceId=1;
UPDATE races SET name="Cadel Road Race" WHERE raceId=2;
UPDATE races SET name="UAE Tour" WHERE raceId=3;
UPDATE races SET name="Omloop Het Nieuwsblad" WHERE raceId=4;
UPDATE races SET name="Strade Bianche" WHERE raceId=5;
UPDATE races SET name="Paris-Nice" WHERE raceId=6;
UPDATE races SET name="Tirreno-Adriatico" WHERE raceId=7;
UPDATE races SET name="Milano-Sanremo" WHERE raceId=8;
UPDATE races SET name="Volta Catalunya" WHERE raceId=9;
UPDATE races SET name="Classic Brugge-De Panne" WHERE raceId=10;
UPDATE races SET name="E3 Saxo Classic" WHERE raceId=11;
UPDATE races SET name="Gent - Wevelgem" WHERE raceId=12;
UPDATE races SET name="Dwars door Vlaanderen" WHERE raceId=13;
UPDATE races SET name="Ronde van Vlaanderen" WHERE raceId=14;
UPDATE races SET name="Itzulia Basque Country" WHERE raceId=15;
UPDATE races SET name="Paris-Roubaix" WHERE raceId=16;
UPDATE races SET name="Amstel Gold Race" WHERE raceId=17;
UPDATE races SET name="La Flèche Wallonne" WHERE raceId=18;
UPDATE races SET name="Liege-Bastogne-Liege" WHERE raceId=19;
UPDATE races SET name="Tour de Romandie" WHERE raceId=20;
UPDATE races SET name="Eschborn-Frankfurt" WHERE raceId=21;
UPDATE races SET name="Critérium du Dauphiné" WHERE raceId=23;
UPDATE races SET name="Tour de Suisse" WHERE raceId=24;
UPDATE races SET name="Tour de France" WHERE raceId=25;
UPDATE races SET name="San Sebastian Klasikoa" WHERE raceId=26;
UPDATE races SET name="Tour de Pologne" WHERE raceId=27;
UPDATE races SET name="Vuelta a España" WHERE raceId=28;
UPDATE races SET name="Bretagne Classic" WHERE raceId=29;
UPDATE races SET name="Renewi Tour" WHERE raceId=30;
UPDATE races SET name="BEMER Cyclassics" WHERE raceId=31;
UPDATE races SET name="GP Québec" WHERE raceId=32;
UPDATE races SET name="GP Montreal" WHERE raceId=33;
UPDATE races SET name="Il Lombardia" WHERE raceId=34;
UPDATE races SET name="Gree - Tour of Guangxi" WHERE raceId=35;
UPDATE races SET name="Volta a la Comunitat Valenciana" WHERE raceId=36;
UPDATE races SET name="Figueira Classic" WHERE raceId=37;
UPDATE races SET name="Tour of Oman" WHERE raceId=38;
UPDATE races SET name="Clasica de Almeria" WHERE raceId=39;
UPDATE races SET name="Volta ao Algarve em Bicicleta" WHERE raceId=40;
UPDATE races SET name="Vuelta a Andalucia Ruta Ciclista Del Sol" WHERE raceId=41;
UPDATE races SET name="Faun-Ardèche Classic" WHERE raceId=42;
UPDATE races SET name="Faun Drôme Classic" WHERE raceId=43;
UPDATE races SET name="Kuurne - Bruxelles - Kuurne" WHERE raceId=44;
UPDATE races SET name="Trofeo Laigueglia" WHERE raceId=45;
UPDATE races SET name="Danilith Nokere Koerse" WHERE raceId=46;
UPDATE races SET name="Milano - Torino" WHERE raceId=47;
UPDATE races SET name="Grand Prix de Denain - Porte du Hainaut" WHERE raceId=48;
UPDATE races SET name="Bredene Koksijde Classic" WHERE raceId=49;
UPDATE races SET name="Gran Premio Miguel Indurain" WHERE raceId=50;
UPDATE races SET name="Scheldeprijs" WHERE raceId=51;
UPDATE races SET name="De Brabantse Pijl - La Flèche Brabançonne" WHERE raceId=52;
UPDATE races SET name="Tour of the Alps" WHERE raceId=53;
UPDATE races SET name="Presidential Cycling Tour of Turkiye" WHERE raceId=54;
UPDATE races SET name="Grand Prix du Morbihan" WHERE raceId=55;
UPDATE races SET name="Tro-Bro Léon" WHERE raceId=56;
UPDATE races SET name="Tour de Hongrie" WHERE raceId=57;
UPDATE races SET name="4 Jours de Dunkerque / Grand Prix des Hauts de France" WHERE raceId=58;
UPDATE races SET name="Tour of Norway" WHERE raceId=59;
UPDATE races SET name="Boucles de la Mayenne - Crédit Mutuel" WHERE raceId=60;
UPDATE races SET name="Circuit Franco-Belge" WHERE raceId=61;
UPDATE races SET name="Brussels Cycling Classic" WHERE raceId=62;
UPDATE races SET name="ZLM Tour" WHERE raceId=63;
UPDATE races SET name="Duracell Dwars door het Hageland" WHERE raceId=64;
UPDATE races SET name="Baloise Belgium Tour" WHERE raceId=65;
UPDATE races SET name="Tour of Slovenia" WHERE raceId=66;
UPDATE races SET name="Tour of Qinghai Lake" WHERE raceId=67;
UPDATE races SET name="Ethias-Tour de Wallonie" WHERE raceId=68;
UPDATE races SET name="Vuelta a Burgos" WHERE raceId=69;
UPDATE races SET name="Arctic Race of Norway" WHERE raceId=70;
UPDATE races SET name="PostNord Danmark Rundt - Tour of Denmark" WHERE raceId=71;
UPDATE races SET name="Deutschland Tour" WHERE raceId=72;
UPDATE races SET name="Maryland Cycling Classic, presented by UnitedHealthcare" WHERE raceId=73;
UPDATE races SET name="Tour of Britain" WHERE raceId=74;
UPDATE races SET name="GP Industria & Artigianato" WHERE raceId=75;
UPDATE races SET name="GP de Fourmies / La Voix du Nord" WHERE raceId=76;
UPDATE races SET name="Coppa Sabatini" WHERE raceId=77;
UPDATE races SET name="Grand Prix de Wallonie" WHERE raceId=78;
UPDATE races SET name="Škoda Tour Luxembourg" WHERE raceId=79;
UPDATE races SET name="SUPER 8 Classic" WHERE raceId=80;
UPDATE races SET name="PETRONAS Le Tour de Langkawi" WHERE raceId=81;
UPDATE races SET name="Sparkassen Münsterland Giro" WHERE raceId=82;
UPDATE races SET name="Paris - Tours Elite" WHERE raceId=84;
UPDATE races SET name="Coppa Bernocchi - GP Banco BPM" WHERE raceId=85;
UPDATE races SET name="Tre Valli Varesine" WHERE raceId=86;
UPDATE races SET name="Tour of Taihu Lake" WHERE raceId=87;
UPDATE races SET name="Gran Piemonte" WHERE raceId=88;
UPDATE races SET name="Tour of Hainan" WHERE raceId=89;
UPDATE races SET name="Giro del Veneto" WHERE raceId=90;
UPDATE races SET name="Japan Cup Cycle Road Race" WHERE raceId=91;
UPDATE races SET name="Veneto Classic" WHERE raceId=92;
UPDATE races SET name="Clàssica Comunitat Valenciana 1969 - Gran Premi València" WHERE raceId=93;
UPDATE races SET name="Trofeo Calvia" WHERE raceId=94;
UPDATE races SET name="Trofeo Ses Salines - Alcudia" WHERE raceId=95;
UPDATE races SET name="Trofeo Serra Tramuntana" WHERE raceId=96;
UPDATE races SET name="Trofeo Pollença" WHERE raceId=97;
UPDATE races SET name="Grand Prix Cycliste de Marseille La Marseillaise" WHERE raceId=98;
UPDATE races SET name="Trofeo Palma - Palma" WHERE raceId=99;
UPDATE races SET name="AlUla Tour" WHERE raceId=100;
UPDATE races SET name="Etoile de Bessèges - Tour du Gard" WHERE raceId=101;
UPDATE races SET name="Tour de Colombie" WHERE raceId=102;
UPDATE races SET name="Muscat Classic" WHERE raceId=103;
UPDATE races SET name="Tour de la Provence" WHERE raceId=104;
UPDATE races SET name="Vuelta Ciclista a la Región de Murcia Costa Cálida" WHERE raceId=105;
UPDATE races SET name="Jaén Paraiso Interior" WHERE raceId=106;
UPDATE races SET name="Classic Var" WHERE raceId=107;
UPDATE races SET name="Tour des Alpes Maritimes et du Var" WHERE raceId=108;
UPDATE races SET name="Tour du Rwanda" WHERE raceId=109;
UPDATE races SET name="O Gran Camiño" WHERE raceId=110;
UPDATE races SET name="Le Samyn" WHERE raceId=111;
UPDATE races SET name="Grand Prix Criquielion" WHERE raceId=112;
UPDATE races SET name="Grote prijs Jean - Pierre Monseré" WHERE raceId=113;
UPDATE races SET name="Classic Loire Atlantique" WHERE raceId=114;
UPDATE races SET name="Cholet - Pays de la Loire" WHERE raceId=115;
UPDATE races SET name="Per Sempre Alfredo" WHERE raceId=116;
UPDATE races SET name="Settimana Internazionale Coppi e Bartali" WHERE raceId=117;
UPDATE races SET name="La Roue Tourangelle Centre Val de Loire - Trophée Groupama Paris Val de Loire" WHERE raceId=118;
UPDATE races SET name="Paris - Camembert" WHERE raceId=119;
UPDATE races SET name="La Route Adélie de Vitré" WHERE raceId=120;
UPDATE races SET name="Volta Limburg Classic" WHERE raceId=121;
UPDATE races SET name="Région Pays de la Loire Tour" WHERE raceId=122;
UPDATE races SET name="Giro della Città Metropolitana di Reggio Calabria" WHERE raceId=123;
UPDATE races SET name="Giro di Sicilia" WHERE raceId=124;
UPDATE races SET name="Classic Grand Besançon Doubs" WHERE raceId=125;
UPDATE races SET name="Tour du Jura Cycliste" WHERE raceId=126;
UPDATE races SET name="Tour du Doubs" WHERE raceId=127;
UPDATE races SET name="Vuelta Asturias Julio Alvarez Mendo" WHERE raceId=128;
UPDATE races SET name="Lotto Famenne Ardenne Classic" WHERE raceId=129;
UPDATE races SET name="Elfstedenronde Brugge" WHERE raceId=130;
UPDATE races SET name="Circuit de Charleroi Wallonie" WHERE raceId=131;
UPDATE races SET name="Tour du Finistère" WHERE raceId=132;
UPDATE races SET name="Veenendaal-Veenendaal Classic" WHERE raceId=134;
UPDATE races SET name="Antwerp Port Epic / Sels Trophy" WHERE raceId=135;
UPDATE races SET name="Ronde van Limburg" WHERE raceId=136;
UPDATE races SET name="Rund um Köln" WHERE raceId=137;
UPDATE races SET name="Heylen Vastgoed Heistse Pijl" WHERE raceId=139;
UPDATE races SET name="Classica Andorra Pirineus" WHERE raceId=140;
UPDATE races SET name="Grosser Preis des Kantons Aargau" WHERE raceId=141;
UPDATE races SET name="Okolo Slovenska / Tour de Slovaquie" WHERE raceId=143;
UPDATE races SET name="Tour of Austria" WHERE raceId=144;
UPDATE races SET name="Sibiu Cycling Tour" WHERE raceId=145;
UPDATE races SET name="Vuelta a Castilla y Leon" WHERE raceId=148;
UPDATE races SET name="Volta a Portugal em Bicicleta" WHERE raceId=149;
UPDATE races SET name="Prueba Villafranca - Ordiziako Klasika" WHERE raceId=150;
UPDATE races SET name="Czech Tour" WHERE raceId=151;
UPDATE races SET name="Circuito de Getxo - Memorial Hermanos Otxoa" WHERE raceId=152;
UPDATE races SET name="La Polynormande" WHERE raceId=153;
UPDATE races SET name="Tour du Limousin-Périgord - Nouvelle Aquitaine" WHERE raceId=154;
UPDATE races SET name="Tour of Leuven - Memorial Jef Scherens" WHERE raceId=155;
UPDATE races SET name="Egmont Cycling Race" WHERE raceId=156;
UPDATE races SET name="Tour Poitou - Charentes en Nouvelle Aquitaine" WHERE raceId=157;
UPDATE races SET name="Druivenkoers - Overijse" WHERE raceId=158;
UPDATE races SET name="Giro della Toscana - Memorial Alfredo Martini" WHERE raceId=159;
UPDATE races SET name="Memorial Marco Pantani" WHERE raceId=160;
UPDATE races SET name="Trofeo Matteotti" WHERE raceId=162;
UPDATE races SET name="Kampioenschap van Vlaanderen" WHERE raceId=163;
UPDATE races SET name="Ixina Gooikse Pijl p/b Lotto" WHERE raceId=164;
UPDATE races SET name="Paris-Chauny" WHERE raceId=165;
UPDATE races SET name="Omloop van het Houtland" WHERE raceId=166;
UPDATE races SET name="Tour of Istanbul" WHERE raceId=167;
UPDATE races SET name="Binche - Chimay - Binche / Mémorial Frank Vandenbroucke" WHERE raceId=168;
UPDATE races SET name="CRO Race" WHERE raceId=169;
UPDATE races SET name="Visit Friesland Elfstedenrace" WHERE raceId=170;
UPDATE races SET name="Paris - Bourges" WHERE raceId=171;
UPDATE races SET name="Tour de Vendée" WHERE raceId=172;
UPDATE races SET name="Coppa Agostoni - Giro delle Brianze" WHERE raceId=173;
UPDATE races SET name="Trofeo Barachi" WHERE raceId=174;
UPDATE races SET name="Chrono des Nations" WHERE raceId=175;
UPDATE races SET name="Tour de Roumanie" WHERE raceId=176;
